extends Node3D
class_name Cups

const LOG_TAG := "Cups"
const DEBUG_CUPS := false

const VISUAL_SCALE: float = 0.014
const VISUAL_ROOT_OFFSET := Vector3(0.0, 0.083, 0.001)
const BODY_CHILD_Y: float = -0.424
const RIM_CHILD_Y: float = 5.914058685302734

const BODY_VERTEX_OFFSET := Vector3(
	0.0,
	VISUAL_ROOT_OFFSET.y + BODY_CHILD_Y * VISUAL_SCALE,
	VISUAL_ROOT_OFFSET.z
)
const RIM_VERTEX_OFFSET := Vector3(
	0.0,
	VISUAL_ROOT_OFFSET.y + (BODY_CHILD_Y + RIM_CHILD_Y) * VISUAL_SCALE,
	VISUAL_ROOT_OFFSET.z
)

const WALL_SIZE := Vector3(0.059, 0.148, 0.005)
const BASE_SIZE := Vector3(0.065, 0.050, 0.065)

const WALL_POSITIONS: Array[Vector3] = [
	Vector3(-0.0421, 0.0896, 0.0351),
	Vector3(-0.0514, 0.0896, -0.0112),
	Vector3(-0.0218, 0.0896, -0.0457),
	Vector3(0.0260, 0.0896, -0.0462),
	Vector3(0.0535, 0.0896, -0.0106),
	Vector3(0.0422, 0.0896, 0.0375),
	Vector3(-0.0004, 0.0882, 0.0552),
]

const WALL_FLARE_RADIANS: float = 0.1396
const CUP_COLLISION_LAYER: int = 1
const CUP_COLLISION_MASK: int = 1

const BALL_DAMP_MARKER_Y: float = 0.124
const BALL_REST_MARKER_Y: float = 0.041

const CUP_REMOVE_LIFT_HEIGHT: float = 0.18
const CUP_REMOVE_LIFT_DURATION: float = 0.18
const CUP_REMOVE_SLIDE_DURATION: float = 0.22
const CUP_REMOVE_EXIT_X: float = 2.0

const FRONT_VERTICES_B64 := (
	"kE84QFP4vsDDLMC/DhOJQFP4vkBXI4e/CydEQFP4vsDDLEC/T7+AQFP4vkBXIwfA7TyNQFP4vkAAAAAAxxJKQFP4vsAAAAAAP8ZBwFP4vsAxQkA/giqNwFP4" +
	"vkC9N4Y17IVHwFP4vsC9N4Y1mx+JwFP4vkBqMoc/7IVHwFP4vsAY7UW/giqNwFP4vkCuLou/0hkVwFP4vsDLLgVAzv15wFP4vkARNgNAJ4cwwFP4vsA5l7o/" +
	"9GpTwFP4vkAvTztA2WAgwFP4vkAQXWhAz57hv1P4vsDBNyVAWU7Iv1P4vkAPDoRA6PmLv1P4vsBcyjtAnBYIv1P4vkBdJIxAPLy3vlP4vsB7SkdATzsIP1P4" +
	"vkD2M4xAYoXLPlP4vsCqYEdA+IysPwAAAAAS2mFAJXggQFP4vkDmdmhA4ULIP1P4vkBa/4NAN6XmP1P4vsAfSiVABteQP1P4vsB0tTtAnX8XQFP4vsD3HwVA" +
	"EB96QFP4vkCmRANA3lhTQFP4vkBQOjtAcxEzQFP4vsDvq7o/xxJKQFP4vsAAAAAA7TyNQFP4vkAAAAAACydEQFP4vsDDLEA/DhOJQFP4vkBPI4c/"
)
const FRONT_NORMALS_B64 := (
	"FjJ3P+Vg1r2JtnO+cVh6Pwr41b2rXzm+aF56P3f21b163zi+FjJ3P+Vg1r2JtnO+8pd+P+Vg1r0AAAAA8pd+P+Vg1r0AAAAAhhx3v5243L0qqXM+oRN+v6xY" +
	"3L2Blm49yxF+vxlX3L3ejnA9cR13v5243L05mnM+QYJ+v5243L0AAAAAQYJ+v5243L0AAAAA+n4+v6MB3L3myig/GF5hvz5a3L0eiOw+r1phvz5a3L33lOw+" +
	"H4Y+v6MB3L3nwig/6ZsQvyZV270pdVE/XJEQvyZV272BfFE/IZO0vhu92r0J/G0/83a0vhu92r1YAW4/W7P1vZPk2b33r3w/Jjj1vZPk2b3dsXw/oDf1Pfw1" +
	"2b0ptHw/B7f1PXY12b1Csnw/nIq0Pu5c2L1TBm4/+pcQP+PE1726hlE/2Xy0Pu5c2L3yCG4/7KIQP+PE170wf1E/PZi0Pu5c2L20A24/gZI+P2UY170tzig/" +
	"mGthP0S/1r0Np+w+oIs+P2UY17361Sg/EW9hP0S/1r3Qmew+8pd+P+Vg1r0AAAAA8pd+P+Vg1r0AAAAAizJ3P+Vg1r0yr3M+oTF3P+Vg1r3gvXM+"
)
const FRONT_UVS_B64 := (
	"zomdPQAAQD9Vih09AAAAP1WKHT0AAEA/zomdPQAAAD8AAAAAAAAAPwAAAAAAAEA/pdgJPwAAQD8AAAA/AAAAPwAAAD8AAEA/pdgJPwAAAD+1Tuw+AABAP7VO" +
	"7D4AAAA/34kdPwAAQD86sRM/AAAAPzqxEz8AAEA/34kdPwAAAD90Yic/AAAAP3RiJz8AAEA/GTsxPwAAAD8ZOzE/AABAP60TOz8AAAA/rRM7PwAAQD9T7EQ/" +
	"AAAAP1PsRD8AAEA/58ROPwAAID+MnVg/AAAAP+fETj8AAAA/jJ1YPwAAQD/nxE4/AABAPyF2Yj8AAEA/xk5sPwAAAD8hdmI/AAAAP8ZObD8AAEA/AACAPwAA" +
	"QD8AAIA/AAAAP1sndj8AAEA/Wyd2PwAAAD8="
)
const FRONT_INDICES_B64 := (
	"AAACAAEAAQADAAAABAACAAUABAABAAIABgAIAAcABwAJAAYABwAIAAoACgALAAcADAAOAA0ADQAPAAwADgAJAA0ADgAGAAkAEAASABEAEQASABMADAAPABAA" +
	"EAARAAwAFAAWABUAFgAXABUAEgAUABMAFAAVABMAGAAaABkAGwAYABkAGAAbABwAFgAaABgAFgAYABcAGAAcABcAHQAfAB4AHgAgAB0AGQAfAB0AHQAbABkA" +
	"IQAjACIAJAAiACMAIAAeACQAJAAjACAA"
)
const FRONT_VERTEX_COUNT: int = 37
const FRONT_INDEX_COUNT: int = 102

const BACK_VERTICES_B64 := (
	"ls2OQFP4vkC9N4Y1XkciQFH4vsDj4qi/Ghg3QFH4vsAAAAAAlN58QFP4vkCJ0QTA8DbRP1H4vsC9ihXAkSgiQFP4vkC9NWvAcQQJP1P4vkDZ243AsU26PlH4" +
	"vsDlYTTAYhXLv1P4vkBOnYXAMzJ8v1H4vsBt5inA3h5WwFP4vkB3hT3Asp8GwFH4vsDG/PC/itiKwFP4vkAhy4i/BwsvwFH4vsBr8S2/eAovwFH4vsBa8S0/" +
	"itiKwFP4vkApy4g/Y0ciQFH4vsAN46g/ls2OQFP4vkC9N4Y1Ghg3QFH4vsAAAAAAj958QFP4vkCJ0QRA"
)
const BACK_NORMALS_B64 := (
	"trl9v0AzCD4AAAAAGaxgv85vCD4Fwes+trl9v0AzCD4AAAAAUaNgv85vCD5x4us+HysQv1AXCT4nwFA/mQ8Qv5QXCT4o01A/2/jzvcUDCj760ns/Mjn1vYID" +
	"Cj4xzns/DAW0PmH+Cj4uH20/Ab6zPh7+Cj6uLG0/Htw9P//NCz46ISg/S8o9P//NCz5pNSg/DTl2P3BDDD51rHI+wTZ2P3BDDD410nI+Nbh9P91gCD6sxSe3" +
	"JLh9P91gCD6sxSe3IHp2v11PBD46A3O+trl9v0AzCD4AAAAAtrl9v0AzCD4AAAAAIHp2v11PBD46A3O+"
)
const BACK_UVS_B64 := (
	"AAAAAAAAgD7OiZ09AAAAAAAAAAAAAAAAzomdPQAAgD7OiR0+AAAAAM6JHT4AAIA+tU5sPgAAgD61Tmw+AAAAAM6JnT4AAIA+zomdPgAAAABC7MQ+AACAPkLs" +
	"xD4AAAAAtU7sPgAAgD61Tuw+AAAAAKXYCT8AAAAApdgJPwAAgD7GTmw/AAAAAAAAgD8AAIA+AACAPwAAAADGTmw/AACAPg=="
)
const BACK_INDICES_B64 := (
	"AAACAAEAAQADAAAAAwABAAQABAAFAAMABgAFAAQABAAHAAYACAAGAAkABgAHAAkACgAIAAsACwAIAAkACwANAAwADAAKAAsADQAOAAwADwAMAA4AEAASABEA" +
	"EQATABAA"
)
const BACK_VERTEX_COUNT: int = 20
const BACK_INDEX_COUNT: int = 48

const RIM_VERTICES_B64 := (
	"5s2HQPgcGD5keYu/c7hxQAAAAAAI4wTARpaFQAAAAAByMom/c7hxQAAAAAAI4wTA5s2HQPgcGD5keYu/iLt1QPgcGD6tFwfAiLt1QPgcGD6tFwfAKxRJQAAA" +
	"AABO0zzAc7hxQAAAAAAI4wTAiLt1QPgcGD6tFwfAlGpMQPgcGD6h9T/AKxRJQAAAAABO0zzAfUEWQPgcGD7bw2zAKxRJQAAAAABO0zzAlGpMQPgcGD6h9T/A" +
	"KxRJQAAAAABO0zzAfUEWQPgcGD7bw2zAdc0TQAAAAAA/5mjA7E6tP/gcGD7LWIXAdc0TQAAAAAA/5mjAfUEWQPgcGD7bw2zAdc0TQAAAAAA/5mjA7E6tP/gc" +
	"GD7LWIXAjXqqPwAAAABzK4PAh9yMPvgcGD657ovAjXqqPwAAAABzK4PA7E6tP/gcGD7LWIXAjXqqPwAAAABzK4PAh9yMPvgcGD657ovA4o+KPgAAAADbpYnA" +
	"h9yMPvgcGD657ovALC5Sv/gcGD7JuYnAqb9OvwAAAAAieofAh9yMPvgcGD657ovAqb9OvwAAAAAieofA4o+KPgAAAADbpYnALC5Sv/gcGD7JuYnA5sruv/gc" +
	"GD7xun3A0uTqvwAAAABslnnALC5Sv/gcGD7JuYnA0uTqvwAAAABslnnAqb9OvwAAAAAieofA5sruv/gcGD7xun3Az74ywPgcGD7xEFjAt9MvwAAAAADbiVTA" +
	"5sruv/gcGD7xun3At9MvwAAAAADbiVTA0uTqvwAAAABslnnA/dxiwPgcGD5r0yTAt9MvwAAAAADbiVTAz74ywPgcGD7xEFjAt9MvwAAAAADbiVTA/dxiwPgc" +
	"GD5r0yTAwyhfwAAAAACBIiLA+1yCwPgcGD4+dc6/wyhfwAAAAACBIiLA/dxiwPgcGD5r0yTAwyhfwAAAAACBIiLA+1yCwPgcGD4+dc6/GzyAwAAAAABMFsu/" +
	"hxqLwPgcGD5blQy/GzyAwAAAAABMFsu/+1yCwPgcGD4+dc6/GzyAwAAAAABMFsu/hxqLwPgcGD5blQy/HdWIwAAAAADDSQq/hxqLwPgcGD4plQw/HdWIwAAA" +
	"AADDSQq/hxqLwPgcGD5blQy/HdWIwAAAAADDSQq/hxqLwPgcGD4plQw/HdWIwAAAAACQSQo/hxqLwPgcGD4plQw//VyCwPgcGD4udc4/HTyAwAAAAAA8Fss/" +
	"HTyAwAAAAAA8Fss/HdWIwAAAAACQSQo/hxqLwPgcGD4plQw//VyCwPgcGD4udc4/Ad1iwPgcGD5j0yRAyChfwAAAAAB5IiJAyChfwAAAAAB5IiJAHTyAwAAA" +
	"AAA8Fss//VyCwPgcGD4udc4/Ad1iwPgcGD5j0yRA174ywPgcGD7pEFhAu9MvwAAAAADSiVRAu9MvwAAAAADSiVRAyChfwAAAAAB5IiJAAd1iwPgcGD5j0yRA" +
	"u9MvwAAAAADSiVRA98ruv/gcGD7pun1A4uTqvwAAAABolnlA98ruv/gcGD7pun1Au9MvwAAAAADSiVRA174ywPgcGD7pEFhA4uTqvwAAAABolnlATS5Sv/gc" +
	"GD7HuYlAy79OvwAAAAAgeodATS5Sv/gcGD7HuYlA4uTqvwAAAABolnlA98ruv/gcGD7pun1Ay79OvwAAAAAgeodARNyMPvgcGD657otAfo+KPgAAAADbpYlA" +
	"RNyMPvgcGD657otAy79OvwAAAAAgeodATS5Sv/gcGD7HuYlAfXqqPwAAAABzK4NAfo+KPgAAAADbpYlARNyMPvgcGD657otAfXqqPwAAAABzK4NARNyMPvgc" +
	"GD657otA206tP/gcGD7LWIVAbM0TQAAAAABD5mhAfXqqPwAAAABzK4NA206tP/gcGD7LWIVAbM0TQAAAAABD5mhA206tP/gcGD7LWIVAcEEWQPgcGD7bw2xA" +
	"JxRJQAAAAABS0zxAbM0TQAAAAABD5mhAcEEWQPgcGD7bw2xAJxRJQAAAAABS0zxAcEEWQPgcGD7bw2xAjGpMQPgcGD6p9T9AJxRJQAAAAABS0zxAhLt1QPgc" +
	"GD61FwdAb7hxQAAAAAAR4wRAhLt1QPgcGD61FwdAJxRJQAAAAABS0zxAjGpMQPgcGD6p9T9Ab7hxQAAAAAAR4wRA5M2HQPgcGD50eYs/RJaFQAAAAACDMok/" +
	"5M2HQPgcGD50eYs/b7hxQAAAAAAR4wRAhLt1QPgcGD61FwdARJaFQAAAAACDMok/jTWMQPgcGD4AAAAAheuJQAAAAAAAAAAAjTWMQPgcGD4AAAAARJaFQAAA" +
	"AACDMok/5M2HQPgcGD50eYs/jTWMQPgcGD4AAAAARpaFQAAAAAByMom/heuJQAAAAAAAAAAARpaFQAAAAAByMom/jTWMQPgcGD4AAAAA5s2HQPgcGD5keYu/" +
	"Yr9+QIKuPT5rDAzA5s2HQPgcGD5keYu/VMmMQIKuPT5Kl5C/5s2HQPgcGD5keYu/Yr9+QIKuPT5rDAzAiLt1QPgcGD6tFwfAYOpTQIKuPT51AEfAiLt1QPgc" +
	"GD6tFwfAYr9+QIKuPT5rDAzAiLt1QPgcGD6tFwfAYOpTQIKuPT51AEfAlGpMQPgcGD6h9T/AYOpTQIKuPT51AEfAoMQbQIKuPT51c3XAfUEWQPgcGD7bw2zA" +
	"fUEWQPgcGD7bw2zAlGpMQPgcGD6h9T/AYOpTQIKuPT51AEfAoMQbQIKuPT51c3XAk6qzP4KuPT4lPYrA7E6tP/gcGD7LWIXA7E6tP/gcGD7LWIXAfUEWQPgc" +
	"GD7bw2zAoMQbQIKuPT51c3XAkgeSPoKuPT7tEJHA7E6tP/gcGD7LWIXAk6qzP4KuPT4lPYrA7E6tP/gcGD7LWIXAkgeSPoKuPT7tEJHAh9yMPvgcGD657ovA" +
	"kgeSPoKuPT7tEJHALC5Sv/gcGD7JuYnAh9yMPvgcGD657ovALC5Sv/gcGD7JuYnAkgeSPoKuPT7tEJHAHeRZv4KuPT5Bx47AHeRZv4KuPT5Bx47A5sruv/gc" +
	"GD7xun3ALC5Sv/gcGD7JuYnA5sruv/gcGD7xun3AHeRZv4KuPT5Bx47Ai433v4KuPT7xhIPAz74ywPgcGD7xEFjAi433v4KuPT7xhIPAh005wIKuPT4m/l/A" +
	"i433v4KuPT7xhIPAz74ywPgcGD7xEFjA5sruv/gcGD7xun3AmC9rwIKuPT5q3yrAz74ywPgcGD7xEFjAh005wIKuPT4m/l/Az74ywPgcGD7xEFjAmC9rwIKu" +
	"PT5q3yrA/dxiwPgcGD5r0yTAmC9rwIKuPT5q3yrATiWHwIKuPT46CNa/+1yCwPgcGD4+dc6/mC9rwIKuPT5q3yrA+1yCwPgcGD4+dc6//dxiwPgcGD5r0yTA" +
	"8DSQwIKuPT6lvRG/+1yCwPgcGD4+dc6/TiWHwIKuPT46CNa/+1yCwPgcGD4+dc6/8DSQwIKuPT6lvRG/hxqLwPgcGD5blQy/8DSQwIKuPT6lvRG/8jSQwIKu" +
	"PT5zvRE/hxqLwPgcGD4plQw/hxqLwPgcGD4plQw/hxqLwPgcGD5blQy/8DSQwIKuPT6lvRG/USWHwIKuPT4gCNY/hxqLwPgcGD4plQw/8jSQwIKuPT5zvRE/" +
	"hxqLwPgcGD4plQw/USWHwIKuPT4gCNY//VyCwPgcGD4udc4//VyCwPgcGD4udc4/oS9rwIKuPT5h3ypAAd1iwPgcGD5j0yRAoS9rwIKuPT5h3ypA/VyCwPgc" +
	"GD4udc4/USWHwIKuPT4gCNY/oS9rwIKuPT5h3ypA174ywPgcGD7pEFhAAd1iwPgcGD5j0yRA174ywPgcGD7pEFhAoS9rwIKuPT5h3ypAkE05wIKuPT4i/l9A" +
	"kE05wIKuPT4i/l9A98ruv/gcGD7pun1A174ywPgcGD7pEFhA98ruv/gcGD7pun1AkE05wIKuPT4i/l9Am433v4KuPT7uhINAm433v4KuPT7uhINAP+RZv4Ku" +
	"PT5Bx45ATS5Sv/gcGD7HuYlAm433v4KuPT7uhINATS5Sv/gcGD7HuYlA98ruv/gcGD7pun1AP+RZv4KuPT5Bx45ALQeSPoKuPT7tEJFARNyMPvgcGD657otA" +
	"P+RZv4KuPT5Bx45ARNyMPvgcGD657otATS5Sv/gcGD7HuYlAgqqzP4KuPT4lPYpARNyMPvgcGD657otALQeSPoKuPT7tEJFARNyMPvgcGD657otAgqqzP4Ku" +
	"PT4lPYpA206tP/gcGD7LWIVAl8QbQIKuPT55c3VA206tP/gcGD7LWIVAgqqzP4KuPT4lPYpA206tP/gcGD7LWIVAl8QbQIKuPT55c3VAcEEWQPgcGD7bw2xA" +
	"l8QbQIKuPT55c3VAV+pTQIKuPT56AEdAjGpMQPgcGD6p9T9AjGpMQPgcGD6p9T9AcEEWQPgcGD7bw2xAl8QbQIKuPT55c3VAhLt1QPgcGD61FwdAjGpMQPgc" +
	"GD6p9T9AV+pTQIKuPT56AEdAhLt1QPgcGD61FwdAV+pTQIKuPT56AEdAWb9+QIKuPT50DAxAWb9+QIKuPT50DAxA5M2HQPgcGD50eYs/hLt1QPgcGD61FwdA" +
	"5M2HQPgcGD50eYs/Wb9+QIKuPT50DAxAUsmMQIKuPT5bl5A/5M2HQPgcGD50eYs/WVqRQIKuPT4AAAAAjTWMQPgcGD4AAAAAWVqRQIKuPT4AAAAA5M2HQPgc" +
	"GD50eYs/UsmMQIKuPT5bl5A/5s2HQPgcGD5keYu/WVqRQIKuPT4AAAAAVMmMQIKuPT5Kl5C/WVqRQIKuPT4AAAAA5s2HQPgcGD5keYu/jTWMQPgcGD4AAAAA" +
	"JMiQQEHVqD28sZS/D/2CQEHVqD3iBRDAYr9+QIKuPT5rDAzAJMiQQEHVqD28sZS/Yr9+QIKuPT5rDAzAVMmMQIKuPT5Kl5C/8u1ZQEHVqD0zpkzAYr9+QIKu" +
	"PT5rDAzAD/2CQEHVqD3iBRDAYr9+QIKuPT5rDAzA8u1ZQEHVqD0zpkzAYOpTQIKuPT51AEfASTAgQEHVqD2panzAYOpTQIKuPT51AEfA8u1ZQEHVqD0zpkzA" +
	"YOpTQIKuPT51AEfASTAgQEHVqD2panzAoMQbQIKuPT51c3XASTAgQEHVqD2panzA28O4P0HVqD10KY7Ak6qzP4KuPT4lPYrAk6qzP4KuPT4lPYrAoMQbQIKu" +
	"PT51c3XASTAgQEHVqD2panzA28O4P0HVqD10KY7AdyyWPkHVqD3VLpXAkgeSPoKuPT7tEJHAkgeSPoKuPT7tEJHAk6qzP4KuPT4lPYrA28O4P0HVqD10KY7A" +
	"dyyWPkHVqD3VLpXAHeRZv4KuPT5Bx47AkgeSPoKuPT7tEJHAHeRZv4KuPT5Bx47AdyyWPkHVqD3VLpXAEhNgv0HVqD2N1JLAEhNgv0HVqD2N1JLAi433v4Ku" +
	"PT7xhIPAHeRZv4KuPT5Bx47Ai433v4KuPT7xhIPAEhNgv0HVqD2N1JLAA5T+v0HVqD1uQIfAh005wIKuPT4m/l/AA5T+v0HVqD1uQIfAwY8+wEHVqD15WWbA" +
	"A5T+v0HVqD1uQIfAh005wIKuPT4m/l/Ai433v4KuPT7xhIPAwY8+wEHVqD15WWbAPNxxwEHVqD3QuC/AmC9rwIKuPT5q3yrAwY8+wEHVqD15WWbAmC9rwIKu" +
	"PT5q3yrAh005wIKuPT4m/l/AJPuKwEHVqD0qG9y/mC9rwIKuPT5q3yrAPNxxwEHVqD3QuC/AmC9rwIKuPT5q3yrAJPuKwEHVqD0qG9y/TiWHwIKuPT46CNa/" +
	"JPuKwEHVqD0qG9y/mkyUwEHVqD1y4BW/8DSQwIKuPT6lvRG/JPuKwEHVqD0qG9y/8DSQwIKuPT6lvRG/TiWHwIKuPT46CNa/mkyUwEHVqD1y4BW/mkyUwEHV" +
	"qD0/4BU/8jSQwIKuPT5zvRE/8jSQwIKuPT5zvRE/8DSQwIKuPT6lvRG/mkyUwEHVqD1y4BW/mkyUwEHVqD0/4BU/JvuKwEHVqD0ZG9w/USWHwIKuPT4gCNY/" +
	"USWHwIKuPT4gCNY/8jSQwIKuPT5zvRE/mkyUwEHVqD0/4BU/USWHwIKuPT4gCNY/QNxxwEHVqD3DuC9AoS9rwIKuPT5h3ypAQNxxwEHVqD3DuC9AUSWHwIKu" +
	"PT4gCNY/JvuKwEHVqD0ZG9w/oS9rwIKuPT5h3ypAyY8+wEHVqD1xWWZAkE05wIKuPT4i/l9AyY8+wEHVqD1xWWZAoS9rwIKuPT5h3ypAQNxxwEHVqD3DuC9A" +
	"kE05wIKuPT4i/l9AFJT+v0HVqD1sQIdAm433v4KuPT7uhINAFJT+v0HVqD1sQIdAkE05wIKuPT4i/l9AyY8+wEHVqD1xWWZANBNgv0HVqD2L1JJAm433v4Ku" +
	"PT7uhINAFJT+v0HVqD1sQIdAm433v4KuPT7uhINANBNgv0HVqD2L1JJAP+RZv4KuPT5Bx45AEyyWPkHVqD3VLpVAP+RZv4KuPT5Bx45ANBNgv0HVqD2L1JJA" +
	"P+RZv4KuPT5Bx45AEyyWPkHVqD3VLpVALQeSPoKuPT7tEJFAEyyWPkHVqD3VLpVAysO4P0HVqD10KY5AgqqzP4KuPT4lPYpAEyyWPkHVqD3VLpVAgqqzP4Ku" +
	"PT4lPYpALQeSPoKuPT7tEJFAysO4P0HVqD10KY5AQDAgQEHVqD2tanxAl8QbQIKuPT55c3VAl8QbQIKuPT55c3VAgqqzP4KuPT4lPYpAysO4P0HVqD10KY5A" +
	"6e1ZQEHVqD07pkxAl8QbQIKuPT55c3VAQDAgQEHVqD2tanxAl8QbQIKuPT55c3VA6e1ZQEHVqD07pkxAV+pTQIKuPT56AEdAV+pTQIKuPT56AEdADf2CQEHV" +
	"qD3mBRBAWb9+QIKuPT50DAxADf2CQEHVqD3mBRBAV+pTQIKuPT56AEdA6e1ZQEHVqD07pkxAWb9+QIKuPT50DAxAIciQQEHVqD3NsZQ/UsmMQIKuPT5bl5A/" +
	"IciQQEHVqD3NsZQ/Wb9+QIKuPT50DAxADf2CQEHVqD3mBRBAIciQQEHVqD3NsZQ/WVqRQIKuPT4AAAAAUsmMQIKuPT5bl5A/WVqRQIKuPT4AAAAAIciQQEHV" +
	"qD3NsZQ/V3qVQEHVqD0AAAAAVMmMQIKuPT5Kl5C/V3qVQEHVqD0AAAAAJMiQQEHVqD28sZS/V3qVQEHVqD0AAAAAVMmMQIKuPT5Kl5C/WVqRQIKuPT4AAAAA" +
	"JMiQQEHVqL28sZS/D/2CQEHVqD3iBRDAJMiQQEHVqD28sZS/D/2CQEHVqD3iBRDAJMiQQEHVqL28sZS/D/2CQEHVqL3iBRDAJPuKwEHVqL0qG9y/mkyUwEHV" +
	"qL1y4BW/mkyUwEHVqD1y4BW/mkyUwEHVqD1y4BW/JPuKwEHVqD0qG9y/JPuKwEHVqL0qG9y/mkyUwEHVqL1y4BW/mkyUwEHVqL0/4BU/mkyUwEHVqD0/4BU/" +
	"mkyUwEHVqD0/4BU/mkyUwEHVqD1y4BW/mkyUwEHVqL1y4BW/mkyUwEHVqL0/4BU/JvuKwEHVqL0ZG9w/JvuKwEHVqD0ZG9w/JvuKwEHVqD0ZG9w/mkyUwEHV" +
	"qD0/4BU/mkyUwEHVqL0/4BU/JvuKwEHVqL0ZG9w/QNxxwEHVqL3DuC9AQNxxwEHVqD3DuC9AQNxxwEHVqD3DuC9AJvuKwEHVqD0ZG9w/JvuKwEHVqL0ZG9w/" +
	"QNxxwEHVqL3DuC9AyY8+wEHVqL1xWWZAyY8+wEHVqD1xWWZAyY8+wEHVqD1xWWZAQNxxwEHVqD3DuC9AQNxxwEHVqL3DuC9AFJT+v0HVqD1sQIdAyY8+wEHV" +
	"qD1xWWZAyY8+wEHVqL1xWWZAFJT+v0HVqD1sQIdAyY8+wEHVqL1xWWZAFJT+v0HVqL1sQIdAFJT+v0HVqL1sQIdANBNgv0HVqD2L1JJAFJT+v0HVqD1sQIdA" +
	"NBNgv0HVqD2L1JJAFJT+v0HVqL1sQIdANBNgv0HVqL2L1JJAEyyWPkHVqD3VLpVANBNgv0HVqD2L1JJANBNgv0HVqL2L1JJAEyyWPkHVqD3VLpVANBNgv0HV" +
	"qL2L1JJAEyyWPkHVqL3VLpVAysO4P0HVqD10KY5AEyyWPkHVqD3VLpVAEyyWPkHVqL3VLpVAysO4P0HVqD10KY5AEyyWPkHVqL3VLpVAysO4P0HVqL10KY5A" +
	"ysO4P0HVqL10KY5AQDAgQEHVqD2tanxAysO4P0HVqD10KY5AQDAgQEHVqD2tanxAysO4P0HVqL10KY5AQDAgQEHVqL2tanxA6e1ZQEHVqD07pkxAQDAgQEHV" +
	"qD2tanxAQDAgQEHVqL2tanxA6e1ZQEHVqD07pkxAQDAgQEHVqL2tanxA6e1ZQEHVqL07pkxA6e1ZQEHVqL07pkxADf2CQEHVqD3mBRBA6e1ZQEHVqD07pkxA" +
	"Df2CQEHVqD3mBRBA6e1ZQEHVqL07pkxADf2CQEHVqL3mBRBADf2CQEHVqL3mBRBAIciQQEHVqD3NsZQ/Df2CQEHVqD3mBRBAIciQQEHVqD3NsZQ/Df2CQEHV" +
	"qL3mBRBAIciQQEHVqL3NsZQ/IciQQEHVqL3NsZQ/V3qVQEHVqD0AAAAAIciQQEHVqD3NsZQ/V3qVQEHVqD0AAAAAIciQQEHVqL3NsZQ/V3qVQEHVqL0AAAAA" +
	"V3qVQEHVqL0AAAAAJMiQQEHVqD28sZS/V3qVQEHVqD0AAAAAJMiQQEHVqD28sZS/V3qVQEHVqL0AAAAAJMiQQEHVqL28sZS/JMiQQEHVqL28sZS/Yr9+QIKu" +
	"Pb5rDAzAD/2CQEHVqL3iBRDAYr9+QIKuPb5rDAzAJMiQQEHVqL28sZS/VMmMQIKuPb5Kl5C/8DSQwIKuPb6lvRG/JPuKwEHVqL0qG9y/TiWHwIKuPb46CNa/" +
	"JPuKwEHVqL0qG9y/8DSQwIKuPb6lvRG/mkyUwEHVqL1y4BW/8jSQwIKuPb5zvRE/mkyUwEHVqL1y4BW/8DSQwIKuPb6lvRG/mkyUwEHVqL1y4BW/8jSQwIKu" +
	"Pb5zvRE/mkyUwEHVqL0/4BU/USWHwIKuPb4gCNY/mkyUwEHVqL0/4BU/8jSQwIKuPb5zvRE/mkyUwEHVqL0/4BU/USWHwIKuPb4gCNY/JvuKwEHVqL0ZG9w/" +
	"USWHwIKuPb4gCNY/oS9rwIKuPb5h3ypAQNxxwEHVqL3DuC9AUSWHwIKuPb4gCNY/QNxxwEHVqL3DuC9AJvuKwEHVqL0ZG9w/yY8+wEHVqL1xWWZAoS9rwIKu" +
	"Pb5h3ypAkE05wIKuPb4i/l9AoS9rwIKuPb5h3ypAyY8+wEHVqL1xWWZAQNxxwEHVqL3DuC9AFJT+v0HVqL1sQIdAkE05wIKuPb4i/l9Am433v4KuPb7uhINA" +
	"kE05wIKuPb4i/l9AFJT+v0HVqL1sQIdAyY8+wEHVqL1xWWZAm433v4KuPb7uhINANBNgv0HVqL2L1JJAFJT+v0HVqL1sQIdANBNgv0HVqL2L1JJAm433v4Ku" +
	"Pb7uhINAP+RZv4KuPb5Bx45AP+RZv4KuPb5Bx45AEyyWPkHVqL3VLpVANBNgv0HVqL2L1JJAEyyWPkHVqL3VLpVAP+RZv4KuPb5Bx45ALQeSPoKuPb7tEJFA" +
	"gqqzP4KuPb4lPYpAEyyWPkHVqL3VLpVALQeSPoKuPb7tEJFAEyyWPkHVqL3VLpVAgqqzP4KuPb4lPYpAysO4P0HVqL10KY5Al8QbQIKuPb55c3VAysO4P0HV" +
	"qL10KY5AgqqzP4KuPb4lPYpAysO4P0HVqL10KY5Al8QbQIKuPb55c3VAQDAgQEHVqL2tanxAl8QbQIKuPb55c3VAV+pTQIKuPb56AEdA6e1ZQEHVqL07pkxA" +
	"6e1ZQEHVqL07pkxAQDAgQEHVqL2tanxAl8QbQIKuPb55c3VAV+pTQIKuPb56AEdAWb9+QIKuPb50DAxADf2CQEHVqL3mBRBADf2CQEHVqL3mBRBA6e1ZQEHV" +
	"qL07pkxAV+pTQIKuPb56AEdAIciQQEHVqL3NsZQ/Wb9+QIKuPb50DAxAUsmMQIKuPb5bl5A/Wb9+QIKuPb50DAxAIciQQEHVqL3NsZQ/Df2CQEHVqL3mBRBA" +
	"WVqRQIKuPb4AAAAAIciQQEHVqL3NsZQ/UsmMQIKuPb5bl5A/IciQQEHVqL3NsZQ/WVqRQIKuPb4AAAAAV3qVQEHVqL0AAAAAV3qVQEHVqL0AAAAAVMmMQIKu" +
	"Pb5Kl5C/JMiQQEHVqL28sZS/VMmMQIKuPb5Kl5C/V3qVQEHVqL0AAAAAWVqRQIKuPb4AAAAAhxqLwPgcGL4plQw/8DSQwIKuPb6lvRG/hxqLwPgcGL5blQy/" +
	"8DSQwIKuPb6lvRG/hxqLwPgcGL4plQw/8jSQwIKuPb5zvRE//VyCwPgcGL4udc4/Ad1iwPgcGL5j0yRAoS9rwIKuPb5h3ypA/VyCwPgcGL4udc4/oS9rwIKu" +
	"Pb5h3ypAUSWHwIKuPb4gCNY/174ywPgcGL7pEFhAoS9rwIKuPb5h3ypAAd1iwPgcGL5j0yRAoS9rwIKuPb5h3ypA174ywPgcGL7pEFhAkE05wIKuPb4i/l9A" +
	"98ruv/gcGL7pun1AkE05wIKuPb4i/l9A174ywPgcGL7pEFhAkE05wIKuPb4i/l9A98ruv/gcGL7pun1Am433v4KuPb7uhINAm433v4KuPb7uhINATS5Sv/gc" +
	"GL7HuYlAP+RZv4KuPb5Bx45ATS5Sv/gcGL7HuYlAm433v4KuPb7uhINA98ruv/gcGL7pun1AP+RZv4KuPb5Bx45ARNyMPvgcGL657otALQeSPoKuPb7tEJFA" +
	"RNyMPvgcGL657otAP+RZv4KuPb5Bx45ATS5Sv/gcGL7HuYlARNyMPvgcGL657otA206tP/gcGL7LWIVAgqqzP4KuPb4lPYpAgqqzP4KuPb4lPYpALQeSPoKu" +
	"Pb7tEJFARNyMPvgcGL657otA206tP/gcGL7LWIVAcEEWQPgcGL7bw2xAl8QbQIKuPb55c3VAl8QbQIKuPb55c3VAgqqzP4KuPb4lPYpA206tP/gcGL7LWIVA" +
	"jGpMQPgcGL6p9T9Al8QbQIKuPb55c3VAcEEWQPgcGL7bw2xAl8QbQIKuPb55c3VAjGpMQPgcGL6p9T9AV+pTQIKuPb56AEdAhLt1QPgcGL61FwdAV+pTQIKu" +
	"Pb56AEdAjGpMQPgcGL6p9T9AV+pTQIKuPb56AEdAhLt1QPgcGL61FwdAWb9+QIKuPb50DAxA5M2HQPgcGL50eYs/Wb9+QIKuPb50DAxAhLt1QPgcGL61FwdA" +
	"Wb9+QIKuPb50DAxA5M2HQPgcGL50eYs/UsmMQIKuPb5bl5A/"
)
const RIM_NORMALS_B64 := (
	"x2Zfv04m3j4/cGU+Tx5Kvwsm3j4lO94+x2Zfv04m3j4/cGU+Tx5Kvwsm3j4lO94+x2Zfv04m3j4/cGU+Tx5Kvwsm3j4lO94+Tx5Kvwsm3j4lO94+miIovwsm" +
	"3j6o4x0/Tx5Kvwsm3j4lO94+Tx5Kvwsm3j4lO94+miIovwsm3j6o4x0/miIovwsm3j6o4x0/2Cz3vgsm3j4WvkI/miIovwsm3j6o4x0/miIovwsm3j6o4x0/" +
	"miIovwsm3j6o4x0/2Cz3vgsm3j4WvkI/2Cz3vgsm3j4WvkI/aYyOvgsm3j73W1s/2Cz3vgsm3j4WvkI/2Cz3vgsm3j4WvkI/2Cz3vgsm3j4WvkI/aYyOvgsm" +
	"3j73W1s/aYyOvgsm3j73W1s/C7hnvQsm3j5iMWY/aYyOvgsm3j73W1s/aYyOvgsm3j73W1s/aYyOvgsm3j73W1s/C7hnvQsm3j5iMWY/C7hnvQsm3j5iMWY/" +
	"C7hnvQsm3j5iMWY/M+AsPi0m3j4EkGI/M+AsPi0m3j4EkGI/C7hnvQsm3j5iMWY/M+AsPi0m3j4EkGI/C7hnvQsm3j5iMWY/M+AsPi0m3j4EkGI/7GjEPgsm" +
	"3j5TslA/7GjEPgsm3j5TslA/M+AsPi0m3j4EkGI/7GjEPgsm3j5TslA/M+AsPi0m3j4EkGI/7GjEPgsm3j5TslA/QgUTPy0m3j6etzE/QgUTPy0m3j6etzE/" +
	"7GjEPgsm3j5TslA/QgUTPy0m3j6etzE/7GjEPgsm3j5TslA/IJk6Pwsm3j5Lkgc/QgUTPy0m3j6etzE/QgUTPy0m3j6etzE/QgUTPy0m3j6etzE/IJk6Pwsm" +
	"3j5Lkgc/IJk6Pwsm3j5Lkgc/gnNWP8gl3j6F0Kk+IJk6Pwsm3j5Lkgc/IJk6Pwsm3j5Lkgc/IJk6Pwsm3j5Lkgc/gnNWP8gl3j6F0Kk+gnNWP8gl3j6F0Kk+" +
	"VtRkP8gl3j6mQ+c9gnNWP8gl3j6F0Kk+gnNWP8gl3j6F0Kk+gnNWP8gl3j6F0Kk+VtRkP8gl3j6mQ+c9VtRkP8gl3j6mQ+c9RdRkPy0m3j4gQ+e9VtRkP8gl" +
	"3j6mQ+c9VtRkP8gl3j6mQ+c9VtRkP8gl3j6mQ+c9RdRkPy0m3j4gQ+e9RdRkPy0m3j4gQ+e9RdRkPy0m3j4gQ+e9YHNWP3Am3j5j0Km+YHNWP3Am3j5j0Km+" +
	"YHNWP3Am3j5j0Km+RdRkPy0m3j4gQ+e9RdRkPy0m3j4gQ+e9YHNWP3Am3j5j0Km+IJk6Py0m3j5Lkge/IJk6Py0m3j5Lkge/IJk6Py0m3j5Lkge/YHNWP3Am" +
	"3j5j0Km+YHNWP3Am3j5j0Km+IJk6Py0m3j5Lkge/QgUTPwsm3j6etzG/QgUTPwsm3j6etzG/QgUTPwsm3j6etzG/IJk6Py0m3j5Lkge/IJk6Py0m3j5Lkge/" +
	"QgUTPwsm3j6etzG/DmnEPuol3j5TslC/DmnEPuol3j5TslC/DmnEPuol3j5TslC/QgUTPwsm3j6etzG/QgUTPwsm3j6etzG/DmnEPuol3j5TslC/duAsPuol" +
	"3j4EkGK/duAsPuol3j4EkGK/duAsPuol3j4EkGK/DmnEPuol3j5TslC/DmnEPuol3j5TslC/duAsPuol3j4EkGK/C7hnvQsm3j5iMWa/C7hnvQsm3j5iMWa/" +
	"C7hnvQsm3j5iMWa/duAsPuol3j4EkGK/duAsPuol3j4EkGK/aYyOvgsm3j73W1u/C7hnvQsm3j5iMWa/C7hnvQsm3j5iMWa/aYyOvgsm3j73W1u/C7hnvQsm" +
	"3j5iMWa/aYyOvgsm3j73W1u/tiz3vgsm3j4WvkK/aYyOvgsm3j73W1u/aYyOvgsm3j73W1u/tiz3vgsm3j4WvkK/aYyOvgsm3j73W1u/tiz3vgsm3j4WvkK/" +
	"miIovwsm3j654x2/tiz3vgsm3j4WvkK/tiz3vgsm3j4WvkK/miIovwsm3j654x2/tiz3vgsm3j4WvkK/miIovwsm3j654x2/miIovwsm3j654x2/YB5Kv+ol" +
	"3j4lO96+YB5Kv+ol3j4lO96+YB5Kv+ol3j4lO96+miIovwsm3j654x2/miIovwsm3j654x2/YB5Kv+ol3j4lO96+6GZfv+ol3j6CcGW+6GZfv+ol3j6CcGW+" +
	"6GZfv+ol3j6CcGW+YB5Kv+ol3j4lO96+YB5Kv+ol3j4lO96+6GZfv+ol3j6CcGW+16Vmvy0m3j4AAAAA16Vmvy0m3j4AAAAA16Vmvy0m3j4AAAAA6GZfv+ol" +
	"3j6CcGW+6GZfv+ol3j6CcGW+16Vmvy0m3j4AAAAAx2Zfv04m3j4/cGU+16Vmvy0m3j4AAAAAx2Zfv04m3j4/cGU+16Vmvy0m3j4AAAAAx2Zfv04m3j4/cGU+" +
	"S61HvuKUeT+si9s9KbRcvuKUeT8mq2I9KbRcvuKUeT8mq2I9KbRcvuKUeT8mq2I9S61HvuKUeT+si9s9S61HvuKUeT+si9s9pBomvuKUeT9Z+xs+S61HvuKU" +
	"eT+si9s9S61HvuKUeT+si9s9S61HvuKUeT+si9s9pBomvuKUeT9Z+xs+pBomvuKUeT9Z+xs+pBomvuKUeT9Z+xs+bjD0veKUeT/gY0A+bjD0veKUeT/gY0A+" +
	"bjD0veKUeT/gY0A+pBomvuKUeT9Z+xs+pBomvuKUeT9Z+xs+bjD0veKUeT/gY0A+ntOMveKUeT+JtVg+ntOMveKUeT+JtVg+ntOMveKUeT+JtVg+bjD0veKU" +
	"eT/gY0A+bjD0veKUeT/gY0A+0epkvOKUeT93aWM+ntOMveKUeT+JtVg+ntOMveKUeT+JtVg+ntOMveKUeT+JtVg+0epkvOKUeT93aWM+0epkvOKUeT93aWM+" +
	"0epkvOKUeT93aWM+bckqPeKUeT9v018+0epkvOKUeT93aWM+bckqPeKUeT9v018+0epkvOKUeT93aWM+bckqPeKUeT9v018+bckqPeKUeT9v018+qwnCPeKU" +
	"eT/cLE4+bckqPeKUeT9v018+qwnCPeKUeT/cLE4+bckqPeKUeT9v018+qwnCPeKUeT/cLE4+gT4RPuKUeT8pki8+qwnCPeKUeT/cLE4+gT4RPuKUeT8pki8+" +
	"qwnCPeKUeT/cLE4+gT4RPuKUeT8pki8+qwnCPeKUeT/cLE4+Nlg4PuKUeT8g7wU+gT4RPuKUeT8pki8+gT4RPuKUeT8pki8+gT4RPuKUeT8pki8+Nlg4PuKU" +
	"eT8g7wU+Nlg4PuKUeT8g7wU+Nlg4PuKUeT8g7wU+SNxTPuKUeT8Nw6c9SNxTPuKUeT8Nw6c9Nlg4PuKUeT8g7wU+SNxTPuKUeT8Nw6c9Nlg4PuKUeT8g7wU+" +
	"exBiPuKUeT95d+Q8SNxTPuKUeT8Nw6c9SNxTPuKUeT8Nw6c9SNxTPuKUeT8Nw6c9exBiPuKUeT95d+Q8exBiPuKUeT95d+Q8exBiPuKUeT95d+Q8vxBiPuKU" +
	"eT95d+S8vxBiPuKUeT95d+S8vxBiPuKUeT95d+S8exBiPuKUeT95d+Q8exBiPuKUeT95d+Q8SNxTPuKUeT+Tw6e9vxBiPuKUeT95d+S8vxBiPuKUeT95d+S8" +
	"vxBiPuKUeT95d+S8SNxTPuKUeT+Tw6e9SNxTPuKUeT+Tw6e9SNxTPuKUeT+Tw6e9Nlg4PuKUeT8g7wW+Nlg4PuKUeT8g7wW+Nlg4PuKUeT8g7wW+SNxTPuKU" +
	"eT+Tw6e9SNxTPuKUeT+Tw6e9Nlg4PuKUeT8g7wW+gT4RPuKUeT8pki++Nlg4PuKUeT8g7wW+gT4RPuKUeT8pki++Nlg4PuKUeT8g7wW+gT4RPuKUeT8pki++" +
	"gT4RPuKUeT8pki++qwnCPeKUeT/cLE6+gT4RPuKUeT8pki++qwnCPeKUeT/cLE6+gT4RPuKUeT8pki++qwnCPeKUeT/cLE6+qwnCPeKUeT/cLE6+bckqPeKU" +
	"eT9v01++bckqPeKUeT9v01++qwnCPeKUeT/cLE6+bckqPeKUeT9v01++qwnCPeKUeT/cLE6+bckqPeKUeT9v01++0epkvOKUeT93aWO+0epkvOKUeT93aWO+" +
	"bckqPeKUeT9v01++0epkvOKUeT93aWO+bckqPeKUeT9v01++ntOMveKUeT+JtVi+0epkvOKUeT93aWO+0epkvOKUeT93aWO+0epkvOKUeT93aWO+ntOMveKU" +
	"eT+JtVi+ntOMveKUeT+JtVi+bjD0veKUeT/gY0C+ntOMveKUeT+JtVi+ntOMveKUeT+JtVi+ntOMveKUeT+JtVi+bjD0veKUeT/gY0C+bjD0veKUeT/gY0C+" +
	"bjD0veKUeT/gY0C+pBomvuKUeT9Z+xu+pBomvuKUeT9Z+xu+pBomvuKUeT9Z+xu+bjD0veKUeT/gY0C+bjD0veKUeT/gY0C+S61HvuKUeT+si9u9pBomvuKU" +
	"eT9Z+xu+pBomvuKUeT9Z+xu+S61HvuKUeT+si9u9pBomvuKUeT9Z+xu+S61HvuKUeT+si9u9S61HvuKUeT+si9u9KbRcvuKUeT8mq2K9S61HvuKUeT+si9u9" +
	"KbRcvuKUeT8mq2K9S61HvuKUeT+si9u9KbRcvuKUeT8mq2K9KbRcvuKUeT8mq2K9z9xjvuKUeT8AAAAAz9xjvuKUeT8AAAAAz9xjvuKUeT8AAAAAKbRcvuKU" +
	"eT8mq2K9KbRcvuKUeT8mq2K9KbRcvuKUeT8mq2I9z9xjvuKUeT8AAAAAKbRcvuKUeT8mq2I9z9xjvuKUeT8AAAAAKbRcvuKUeT8mq2I9z9xjvuKUeT8AAAAA" +
	"MZkaPzUmSD+9xh6+xt4LPyQmSD/WyZm+xt4LPyQmSD/WyZm+MZkaPzUmSD+9xh6+xt4LPyQmSD/WyZm+QpkaPzUmSD+9xh6+wLToPiQmSD+Uhtq+xt4LPyQm" +
	"SD/WyZm+xt4LPyQmSD/WyZm+xt4LPyQmSD/WyZm+wLToPiQmSD+Uhtq+wLToPiQmSD+Uhtq+zAyrPiQmSD8NxAa/wLToPiQmSD+Uhtq+wLToPiQmSD+Uhtq+" +
	"wLToPiQmSD+Uhtq+zAyrPiQmSD8NxAa/zAyrPiQmSD8NxAa/zAyrPiQmSD8NxAa/BktFPiQmSD8UzRe/BktFPiQmSD8UzRe/BktFPiQmSD8UzRe/zAyrPiQm" +
	"SD8NxAa/zAyrPiQmSD8NxAa/BktFPiQmSD8UzRe/wFsgPSQmSD9NTB+/wFsgPSQmSD9NTB+/wFsgPSQmSD9NTB+/BktFPiQmSD8UzRe/BktFPiQmSD8UzRe/" +
	"wFsgPSQmSD9NTB+/kUTvvSQmSD8yyRy/wFsgPSQmSD9NTB+/kUTvvSQmSD8yyRy/wFsgPSQmSD9NTB+/kUTvvSQmSD8yyRy/kUTvvSQmSD8yyRy/juuHviQm" +
	"SD8ibBC/kUTvvSQmSD8yyRy/juuHviQmSD8ibBC/kUTvvSQmSD8yyRy/juuHviQmSD8ibBC/jXvLviQmSD/o9/W+juuHviQmSD8ibBC/jXvLviQmSD/o9/W+" +
	"juuHviQmSD8ibBC/jXvLviQmSD/o9/W+juuHviQmSD8ibBC/jXvLviQmSD/o9/W+NiEBvyQmSD8Bo7u+NiEBvyQmSD8Bo7u+jXvLviQmSD/o9/W+NiEBvyQm" +
	"SD8Bo7u+jXvLviQmSD/o9/W+nWcUvyQmSD/RB2u+NiEBvyQmSD8Bo7u+NiEBvyQmSD8Bo7u+NiEBvyQmSD8Bo7u+nWcUvyQmSD/RB2u+nWcUvyQmSD/RB2u+" +
	"nWcUvyQmSD/RB2u+zVoevyQmSD/2CaC9zVoevyQmSD/2CaC9nWcUvyQmSD/RB2u+zVoevyQmSD/2CaC9nWcUvyQmSD/RB2u+zVoevyQmSD/2CaC9vFoevyQm" +
	"SD/2CaA9zVoevyQmSD/2CaA9zVoevyQmSD/2CaA9zVoevyQmSD/2CaC9zVoevyQmSD/2CaC9vFoevyQmSD/2CaA9nWcUvyQmSD/RB2s+nWcUvyQmSD+OB2s+" +
	"nWcUvyQmSD+OB2s+zVoevyQmSD/2CaA9vFoevyQmSD/2CaA9nWcUvyQmSD+OB2s+NiEBvyQmSD8Bo7s+NiEBvyQmSD8Bo7s+NiEBvyQmSD8Bo7s+nWcUvyQm" +
	"SD+OB2s+nWcUvyQmSD/RB2s+NiEBvyQmSD8Bo7s+jXvLviQmSD/o9/U+jXvLviQmSD/o9/U+jXvLviQmSD/o9/U+NiEBvyQmSD8Bo7s+NiEBvyQmSD8Bo7s+" +
	"jXvLviQmSD/o9/U+juuHviQmSD8ibBA/juuHviQmSD8ibBA/juuHviQmSD8ibBA/jXvLviQmSD/o9/U+jXvLviQmSD/o9/U+kUTvvSQmSD8yyRw/juuHviQm" +
	"SD8ibBA/juuHviQmSD8ibBA/juuHviQmSD8ibBA/kUTvvSQmSD8yyRw/kUTvvSQmSD8yyRw/tFogPSQmSD9eTB8/kUTvvSQmSD8yyRw/kUTvvSQmSD8yyRw/" +
	"kUTvvSQmSD8yyRw/tFogPSQmSD9eTB8/tFogPSQmSD9eTB8/tFogPSQmSD9eTB8/BktFPhQmSD8lzRc/BktFPiQmSD8lzRc/tFogPSQmSD9eTB8/BktFPiQm" +
	"SD8lzRc/tFogPSQmSD9eTB8/BktFPhQmSD8lzRc/zAyrPiQmSD8NxAY/zAyrPiQmSD8NxAY/zAyrPiQmSD8NxAY/BktFPiQmSD8lzRc/BktFPhQmSD8lzRc/" +
	"wLToPiQmSD+Uhto+zAyrPiQmSD8NxAY/zAyrPiQmSD8NxAY/zAyrPiQmSD8NxAY/wLToPiQmSD+Uhto+wLToPiQmSD+Uhto+wLToPiQmSD+Uhto+xt4LPyQm" +
	"SD/3yZk+xt4LPyQmSD/WyZk+xt4LPyQmSD/3yZk+wLToPiQmSD+Uhto+wLToPiQmSD+Uhto+xt4LPyQmSD/WyZk+UpkaPyQmSD8Axx4+UpkaPxQmSD8Axx4+" +
	"UpkaPyQmSD8Axx4+xt4LPyQmSD/WyZk+xt4LPyQmSD/3yZk+UpkaPyQmSD8Axx4++pwfPyQmSD8AAAAAUpkaPxQmSD8Axx4++pwfPyQmSD8AAAAAUpkaPyQm" +
	"SD8Axx4++pwfPyQmSD8AAAAAQpkaPzUmSD+9xh6++pwfPyQmSD8AAAAAMZkaPzUmSD+9xh6++pwfPyQmSD8AAAAAQpkaPzUmSD+9xh6++pwfPyQmSD8AAAAA" +
	"DvV3PwAAAABUqH6+3gVuPwAAAADAery+DvV3PwAAAABUqH6+3gVuPwAAAADAery+DvV3PwAAAABUqH6+3gVuPwAAAADAery+DvV3vwAAAACXqH6+QPt9vwAA" +
	"AABLVwC+QPt9vwAAAABLVwC+QPt9vwAAAABLVwC+DvV3vwAAAACXqH6+DvV3vwAAAACXqH6+QPt9vwAAAABLVwC+QPt9vwAAAABLVwA+QPt9vwAAAABLVwA+" +
	"QPt9vwAAAABLVwA+QPt9vwAAAABLVwC+QPt9vwAAAABLVwC+QPt9vwAAAABLVwA+3gVuvwAAAADAerw+3gVuvwAAAADAerw+3gVuvwAAAADAerw+QPt9vwAA" +
	"AABLVwA+QPt9vwAAAABLVwA+3gVuvwAAAADAerw+vRtPvwAAAAAUeRY/vRtPvwAAAAAUeRY/vRtPvwAAAAAUeRY/3gVuvwAAAADAerw+3gVuvwAAAADAerw+" +
	"vRtPvwAAAAAUeRY/OC4jvwAAAABXQEU/OC4jvwAAAABXQEU/OC4jvwAAAABXQEU/vRtPvwAAAAAUeRY/vRtPvwAAAAAUeRY/tf/ZvgAAAAC+omc/OC4jvwAA" +
	"AABXQEU/OC4jvwAAAABXQEU/tf/ZvgAAAAC+omc/OC4jvwAAAABXQEU/tf/ZvgAAAAC+omc/tf/ZvgAAAAC+omc/zuA/vgAAAAApd3s/tf/ZvgAAAAC+omc/" +
	"zuA/vgAAAAApd3s/tf/ZvgAAAAC+omc/zuA/vgAAAAApd3s/kZiAPQAAAACzfn8/zuA/vgAAAAApd3s/zuA/vgAAAAApd3s/kZiAPQAAAACzfn8/zuA/vgAA" +
	"AAApd3s/kZiAPQAAAACzfn8/ejeePgAAAABoeHM/kZiAPQAAAACzfn8/kZiAPQAAAACzfn8/ejeePgAAAABoeHM/kZiAPQAAAACzfn8/ejeePgAAAABoeHM/" +
	"ejeePgAAAABoeHM/9SsJPwAAAADhJVg/ejeePgAAAABoeHM/9SsJPwAAAADhJVg/ejeePgAAAABoeHM/9SsJPwAAAADhJVg/tp06PwAAAAB5Pi8/9SsJPwAA" +
	"AADhJVg/9SsJPwAAAADhJVg/tp06PwAAAAB5Pi8/9SsJPwAAAADhJVg/tp06PwAAAAB5Pi8/tp06PwAAAAB5Pi8/qFVgPwAAAAB2qPY+tp06PwAAAAB5Pi8/" +
	"qFVgPwAAAAB2qPY+tp06PwAAAAB5Pi8/qFVgPwAAAAB2qPY+qFVgPwAAAAB2qPY+DvV3PwAAAACXqH4+qFVgPwAAAAB2qPY+DvV3PwAAAACXqH4+qFVgPwAA" +
	"AAB2qPY+DvV3PwAAAACXqH4+DvV3PwAAAACXqH4+AACAPwAAAAAAAAAADvV3PwAAAACXqH4+AACAPwAAAAAAAAAADvV3PwAAAACXqH4+AACAPwAAAAAAAAAA" +
	"AACAPwAAAAAAAAAADvV3PwAAAABUqH6+AACAPwAAAAAAAAAADvV3PwAAAABUqH6+AACAPwAAAAAAAAAADvV3PwAAAABUqH6+MZkaPzUmSL+9xh6+Tx8VP/CH" +
	"R7+IKmy+Tx8VP/CHR7+IKmy+Tx8VP/CHR7+IKmy+MZkaPzUmSL+9xh6+MZkaPzUmSL+9xh6+zVoevyQmSL/2CaC9sFgbv9+HR7+cix++sFgbv9+HR7+cix++" +
	"sFgbv9+HR7+cix++zVoevyQmSL/2CaC9zVoevyQmSL/2CaC9vFoevyQmSL/2CaA9zVoevyQmSL/2CaC9zVoevyQmSL/2CaC9zVoevyQmSL/2CaC9vFoevyQm" +
	"SL/2CaA9vFoevyQmSL/2CaA9nWcUvyQmSL/RB2s+vFoevyQmSL/2CaA9vFoevyQmSL/2CaA9vFoevyQmSL/2CaA9nWcUvyQmSL/RB2s+nWcUvyQmSL/RB2s+" +
	"nWcUvyQmSL/RB2s+NiEBvyQmSL8Bo7s+RyEBvyQmSL8Bo7s+nWcUvyQmSL/RB2s+RyEBvyQmSL8Bo7s+nWcUvyQmSL/RB2s+jXvLviQmSL/G9/U+NiEBvyQm" +
	"SL8Bo7s+jXvLviQmSL/o9/U+NiEBvyQmSL8Bo7s+jXvLviQmSL/G9/U+RyEBvyQmSL8Bo7s+juuHviQmSL8ibBA/jXvLviQmSL/o9/U+juuHviQmSL8ibBA/" +
	"jXvLviQmSL/o9/U+juuHviQmSL8ibBA/jXvLviQmSL/G9/U+juuHviQmSL8ibBA/kUTvvSQmSL8yyRw/juuHviQmSL8ibBA/kUTvvSQmSL8yyRw/juuHviQm" +
	"SL8ibBA/kUTvvSQmSL8yyRw/kUTvvSQmSL8yyRw/tFogPSQmSL9eTB8/kUTvvSQmSL8yyRw/tFogPSQmSL9eTB8/kUTvvSQmSL8yyRw/tFogPSQmSL9eTB8/" +
	"BktFPiQmSL8lzRc/tFogPSQmSL9eTB8/tFogPSQmSL9eTB8/tFogPSQmSL9eTB8/BktFPiQmSL8lzRc/BktFPiQmSL8lzRc/zAyrPiQmSL8NxAY/BktFPiQm" +
	"SL8lzRc/BktFPiQmSL8lzRc/BktFPiQmSL8lzRc/zAyrPiQmSL8NxAY/zAyrPiQmSL8NxAY/zAyrPiQmSL8NxAY/wLToPiQmSL9yhto+wLToPiQmSL9yhto+" +
	"wLToPiQmSL9yhto+zAyrPiQmSL8NxAY/zAyrPiQmSL8NxAY/wLToPiQmSL9yhto+xt4LPyQmSL/WyZk+xt4LPyQmSL/WyZk+xt4LPyQmSL/WyZk+wLToPiQm" +
	"SL9yhto+wLToPiQmSL9yhto+UpkaPyQmSL8Axx4+xt4LPyQmSL/WyZk+UpkaPyQmSL8Axx4+xt4LPyQmSL/WyZk+UpkaPyQmSL8Axx4+xt4LPyQmSL/WyZk+" +
	"+pwfPyQmSL8AAAAAUpkaPyQmSL8Axx4+UpkaPyQmSL8Axx4+UpkaPyQmSL8Axx4++pwfPyQmSL8AAAAA+pwfPyQmSL8AAAAA+pwfPyQmSL8AAAAAMZkaPzUm" +
	"SL+9xh6+MZkaPzUmSL+9xh6+MZkaPzUmSL+9xh6++pwfPyQmSL8AAAAA+pwfPyQmSL8AAAAA8pRlPqZ7eb8AAAAA8pRlPqZ7eb8AAAAA8pRlPqZ7eb8AAAAA" +
	"8pRlPqZ7eb8AAAAA8pRlPqZ7eb8AAAAA8pRlPqZ7eb8AAAAAKy9JPqZ7eb9ZNN29Nlg4PuKUeb8g7wW+Nlg4PuKUeb8g7wW+Ky9JPqZ7eb9ZNN29Nlg4PuKU" +
	"eb8g7wW+Ky9JPqZ7eb9ZNN29xD4RPuKUeb8pki++Nlg4PuKUeb8g7wW+Nlg4PuKUeb8g7wW+Nlg4PuKUeb8g7wW+xD4RPuKUeb8pki++xD4RPuKUeb8pki++" +
	"qwnCPeKUeb/cLE6+xD4RPuKUeb8pki++xD4RPuKUeb8pki++xD4RPuKUeb8pki++qwnCPeKUeb/cLE6+qwnCPeKUeb/cLE6+qwnCPeKUeb/cLE6+bckqPeKU" +
	"eb9v01++bckqPeKUeb9v01++bckqPeKUeb9v01++qwnCPeKUeb/cLE6+qwnCPeKUeb/cLE6+bckqPeKUeb9v01++0epkvOKUeb93aWO+0epkvOKUeb93aWO+" +
	"0epkvOKUeb93aWO+bckqPeKUeb9v01++bckqPeKUeb9v01++0epkvOKUeb93aWO+ntOMveKUeb+JtVi+ntOMveKUeb+JtVi+ntOMveKUeb+JtVi+0epkvOKU" +
	"eb93aWO+0epkvOKUeb93aWO+ntOMveKUeb+JtVi+bjD0veKUeb/gY0C+bjD0veKUeb/gY0C+bjD0veKUeb/gY0C+ntOMveKUeb+JtVi+ntOMveKUeb+JtVi+" +
	"pBomvuKUeb9Z+xu+bjD0veKUeb/gY0C+bjD0veKUeb/gY0C+bjD0veKUeb/gY0C+pBomvuKUeb9Z+xu+pBomvuKUeb9Z+xu+S61HvuKUeb8zjNu9pBomvuKU" +
	"eb9Z+xu+pBomvuKUeb9Z+xu+pBomvuKUeb9Z+xu+S61HvuKUeb8zjNu9S61HvuKUeb+si9u9wHVVvqZ7eb+WB6m9S61HvuKUeb+si9u9S61HvuKUeb8zjNu9" +
	"S61HvuKUeb+si9u9wHVVvqZ7eb+WB6m9wHVVvqZ7eb+WB6m9"
)
const RIM_UVS_B64 := (
	"AAAAABxJEj4K1yM9AAAAAAAAAAAAAAAACtcjPQAAAAAAAAAAHEkSPgrXIz0cSRI+CtcjPRxJEj4K16M9AAAAAArXIz0AAAAACtcjPRxJEj4K16M9HEkSPgrX" +
	"oz0AAAAAj8L1PRxJEj4K16M9AAAAAArXoz0cSRI+CtejPQAAAACPwvU9HEkSPo/C9T0AAAAACtcjPhxJEj6PwvU9AAAAAI/C9T0cSRI+j8L1PQAAAAAK1yM+" +
	"HEkSPgrXIz4AAAAAzcxMPhxJEj4K1yM+AAAAAArXIz4cSRI+CtcjPgAAAADNzEw+HEkSPs3MTD4AAAAAzcxMPhxJEj6PwnU+HEkSPo/CdT4AAAAAzcxMPhxJ" +
	"Ej6PwnU+AAAAAM3MTD4AAAAAj8J1PhxJEj4pXI8+HEkSPilcjz4AAAAAj8J1PhxJEj4pXI8+AAAAAI/CdT4AAAAAKVyPPhxJEj4K16M+HEkSPgrXoz4AAAAA" +
	"KVyPPhxJEj4K16M+AAAAAClcjz4AAAAA7FG4PhxJEj4K16M+AAAAAArXoz4cSRI+CtejPgAAAADsUbg+HEkSPuxRuD4AAAAAzczMPhxJEj7sUbg+AAAAAOxR" +
	"uD4cSRI+7FG4PgAAAADNzMw+HEkSPs3MzD4AAAAArkfhPhxJEj7NzMw+AAAAAM3MzD4cSRI+zczMPgAAAACuR+E+HEkSPq5H4T4AAAAAj8L1PhxJEj6uR+E+" +
	"AAAAAK5H4T4cSRI+rkfhPgAAAACPwvU+HEkSPo/C9T4AAAAAj8L1PhxJEj64HgU/HEkSPrgeBT8AAAAAuB4FPwAAAACPwvU+AAAAAI/C9T4cSRI+uB4FPxxJ" +
	"Ej4pXA8/HEkSPilcDz8AAAAAKVwPPwAAAAC4HgU/AAAAALgeBT8cSRI+KVwPPxxJEj6amRk/HEkSPpqZGT8AAAAAmpkZPwAAAAApXA8/AAAAAClcDz8cSRI+" +
	"mpkZPwAAAAAK1yM/HEkSPgrXIz8AAAAACtcjPxxJEj6amRk/AAAAAJqZGT8cSRI+CtcjPwAAAAB7FC4/HEkSPnsULj8AAAAAexQuPxxJEj4K1yM/AAAAAArX" +
	"Iz8cSRI+exQuPwAAAADsUTg/HEkSPuxROD8AAAAA7FE4PxxJEj57FC4/AAAAAHsULj8cSRI+XI9CPwAAAADsUTg/AAAAAOxROD8cSRI+XI9CPwAAAADsUTg/" +
	"HEkSPlyPQj8cSRI+zcxMPwAAAABcj0I/AAAAAFyPQj8cSRI+zcxMPwAAAABcj0I/HEkSPs3MTD8cSRI+PQpXPwAAAADNzEw/AAAAAM3MTD8cSRI+PQpXPwAA" +
	"AADNzEw/HEkSPj0KVz8cSRI+PQpXPwAAAACuR2E/HEkSPq5HYT8AAAAArkdhPxxJEj49Clc/AAAAAD0KVz8cSRI+rkdhPwAAAAAfhWs/HEkSPh+Faz8AAAAA" +
	"H4VrPxxJEj6uR2E/AAAAAK5HYT8cSRI+H4VrPwAAAACPwnU/HEkSPo/CdT8AAAAAj8J1PxxJEj4fhWs/AAAAAB+Faz8cSRI+j8J1PxxJEj4AAIA/AAAAAI/C" +
	"dT8AAAAAAACAPwAAAACPwnU/HEkSPgAAgD8cSRI+CtcjPRpJkj4AAAAAHEkSPgAAAAAaSZI+AAAAABxJEj4K1yM9GkmSPgrXIz0cSRI+CtejPRpJkj4K1yM9" +
	"HEkSPgrXIz0aSZI+CtcjPRxJEj4K16M9GkmSPgrXoz0cSRI+CtejPRpJkj6PwvU9GkmSPo/C9T0cSRI+j8L1PRxJEj4K16M9HEkSPgrXoz0aSZI+j8L1PRpJ" +
	"kj4K1yM+GkmSPgrXIz4cSRI+CtcjPhxJEj6PwvU9HEkSPo/C9T0aSZI+zcxMPhpJkj4K1yM+HEkSPgrXIz4aSZI+CtcjPhxJEj7NzEw+GkmSPs3MTD4cSRI+" +
	"zcxMPhpJkj6PwnU+HEkSPs3MTD4cSRI+j8J1PhxJEj7NzEw+GkmSPo/CdT4aSZI+j8J1PhpJkj4pXI8+HEkSPo/CdT4cSRI+KVyPPhxJEj6PwnU+GkmSPilc" +
	"jz4aSZI+CtejPhxJEj4pXI8+GkmSPgrXoz4aSZI+KVyPPhpJkj4K16M+HEkSPilcjz4cSRI+7FG4PhpJkj4K16M+HEkSPgrXoz4aSZI+CtejPhxJEj7sUbg+" +
	"GkmSPuxRuD4cSRI+7FG4PhpJkj7NzMw+GkmSPs3MzD4cSRI+7FG4PhpJkj7NzMw+HEkSPuxRuD4cSRI+rkfhPhpJkj7NzMw+HEkSPs3MzD4aSZI+zczMPhxJ" +
	"Ej6uR+E+GkmSPq5H4T4cSRI+rkfhPhpJkj6PwvU+GkmSPo/C9T4cSRI+j8L1PhxJEj6uR+E+HEkSPq5H4T4aSZI+uB4FPxpJkj6PwvU+HEkSPo/C9T4aSZI+" +
	"j8L1PhxJEj64HgU/GkmSPrgeBT8cSRI+uB4FPxxJEj4pXA8/GkmSPilcDz8cSRI+KVwPPxpJkj64HgU/HEkSPrgeBT8aSZI+KVwPPxpJkj6amRk/HEkSPilc" +
	"Dz8cSRI+mpkZPxxJEj4pXA8/GkmSPpqZGT8aSZI+mpkZPxpJkj4K1yM/HEkSPpqZGT8cSRI+CtcjPxxJEj6amRk/GkmSPgrXIz8aSZI+CtcjPxpJkj57FC4/" +
	"GkmSPnsULj8cSRI+CtcjPxpJkj57FC4/HEkSPgrXIz8cSRI+exQuPxpJkj7sUTg/GkmSPuxROD8cSRI+exQuPxpJkj7sUTg/HEkSPnsULj8cSRI+XI9CPxpJ" +
	"kj7sUTg/HEkSPuxROD8aSZI+7FE4PxxJEj5cj0I/GkmSPlyPQj8cSRI+zcxMPxpJkj5cj0I/HEkSPlyPQj8aSZI+XI9CPxxJEj7NzEw/GkmSPs3MTD8cSRI+" +
	"zcxMPxpJkj49Clc/GkmSPj0KVz8cSRI+PQpXPxxJEj7NzEw/HEkSPs3MTD8aSZI+rkdhPxxJEj49Clc/HEkSPj0KVz8aSZI+rkdhPxxJEj49Clc/GkmSPq5H" +
	"YT8aSZI+rkdhPxpJkj4fhWs/HEkSPq5HYT8cSRI+H4VrPxxJEj6uR2E/GkmSPh+Faz8aSZI+H4VrPxxJEj6PwnU/GkmSPo/CdT8cSRI+j8J1PxpJkj4fhWs/" +
	"HEkSPh+Faz8aSZI+AACAPxxJEj6PwnU/GkmSPgAAgD8aSZI+j8J1PxpJkj4AAIA/HEkSPo/CdT8cSRI+AAAAAKht2z4K1yM9qG3bPgrXIz0aSZI+AAAAAKht" +
	"2z4K1yM9GkmSPgAAAAAaSZI+CtejPaht2z4K1yM9GkmSPgrXIz2obds+CtcjPRpJkj4K16M9qG3bPgrXoz0aSZI+j8L1Paht2z4K16M9GkmSPgrXoz2obds+" +
	"CtejPRpJkj6PwvU9qG3bPo/C9T0aSZI+j8L1Paht2z4K1yM+qG3bPgrXIz4aSZI+CtcjPhpJkj6PwvU9GkmSPo/C9T2obds+CtcjPqht2z7NzEw+qG3bPs3M" +
	"TD4aSZI+zcxMPhpJkj4K1yM+GkmSPgrXIz6obds+zcxMPqht2z6PwnU+GkmSPs3MTD4aSZI+j8J1PhpJkj7NzEw+qG3bPo/CdT6obds+j8J1Pqht2z4pXI8+" +
	"GkmSPo/CdT4aSZI+KVyPPhpJkj6PwnU+qG3bPilcjz6obds+CtejPhpJkj4pXI8+qG3bPgrXoz6obds+KVyPPqht2z4K16M+GkmSPilcjz4aSZI+CtejPqht" +
	"2z7sUbg+qG3bPuxRuD4aSZI+CtejPqht2z7sUbg+GkmSPgrXoz4aSZI+zczMPqht2z7sUbg+GkmSPuxRuD6obds+7FG4PhpJkj7NzMw+qG3bPs3MzD4aSZI+" +
	"zczMPqht2z6uR+E+qG3bPq5H4T4aSZI+zczMPqht2z6uR+E+GkmSPs3MzD4aSZI+rkfhPqht2z6PwvU+qG3bPo/C9T4aSZI+j8L1PhpJkj6uR+E+GkmSPq5H" +
	"4T6obds+j8L1Pqht2z64HgU/qG3bPrgeBT8aSZI+uB4FPxpJkj6PwvU+GkmSPo/C9T6obds+uB4FPxpJkj4pXA8/qG3bPilcDz8aSZI+KVwPP6ht2z64HgU/" +
	"GkmSPrgeBT+obds+KVwPPxpJkj6amRk/qG3bPpqZGT8aSZI+mpkZP6ht2z4pXA8/GkmSPilcDz+obds+mpkZPxpJkj4K1yM/qG3bPgrXIz8aSZI+CtcjP6ht" +
	"2z6amRk/GkmSPpqZGT+obds+exQuP6ht2z4K1yM/GkmSPgrXIz+obds+CtcjPxpJkj57FC4/qG3bPnsULj8aSZI+7FE4P6ht2z57FC4/GkmSPnsULj+obds+" +
	"exQuPxpJkj7sUTg/qG3bPuxROD8aSZI+7FE4P6ht2z5cj0I/qG3bPlyPQj8aSZI+7FE4P6ht2z5cj0I/GkmSPuxROD8aSZI+XI9CP6ht2z7NzEw/qG3bPs3M" +
	"TD8aSZI+zcxMPxpJkj5cj0I/GkmSPlyPQj+obds+PQpXP6ht2z7NzEw/GkmSPs3MTD+obds+zcxMPxpJkj49Clc/qG3bPj0KVz8aSZI+PQpXPxpJkj6uR2E/" +
	"qG3bPq5HYT8aSZI+rkdhP6ht2z49Clc/GkmSPj0KVz+obds+rkdhPxpJkj4fhWs/qG3bPh+Faz8aSZI+H4VrP6ht2z6uR2E/GkmSPq5HYT+obds+H4VrP6ht" +
	"2z6PwnU/GkmSPh+Faz8aSZI+j8J1PxpJkj4fhWs/qG3bPo/CdT+obds+AACAPxpJkj6PwnU/qG3bPgAAgD+obds+j8J1P6ht2z4AAIA/GkmSPo/CdT8aSZI+" +
	"AAAAACxJEj8K1yM9qG3bPgAAAACobds+CtcjPaht2z4AAAAALEkSPwrXIz0sSRI/zczMPixJEj+uR+E+LEkSP65H4T6obds+rkfhPqht2z7NzMw+qG3bPs3M" +
	"zD4sSRI/rkfhPixJEj+PwvU+LEkSP4/C9T6obds+j8L1Pqht2z6uR+E+qG3bPq5H4T4sSRI/j8L1PixJEj+4HgU/LEkSP7geBT+obds+uB4FP6ht2z6PwvU+" +
	"qG3bPo/C9T4sSRI/uB4FPyxJEj8pXA8/LEkSPylcDz+obds+KVwPP6ht2z64HgU/qG3bPrgeBT8sSRI/KVwPPyxJEj+amRk/LEkSP5qZGT+obds+mpkZP6ht" +
	"2z4pXA8/qG3bPilcDz8sSRI/CtcjP6ht2z6amRk/qG3bPpqZGT8sSRI/CtcjP6ht2z6amRk/LEkSPwrXIz8sSRI/CtcjPyxJEj97FC4/qG3bPgrXIz+obds+" +
	"exQuP6ht2z4K1yM/LEkSP3sULj8sSRI/7FE4P6ht2z57FC4/qG3bPnsULj8sSRI/7FE4P6ht2z57FC4/LEkSP+xROD8sSRI/XI9CP6ht2z7sUTg/qG3bPuxR" +
	"OD8sSRI/XI9CP6ht2z7sUTg/LEkSP1yPQj8sSRI/XI9CPyxJEj/NzEw/qG3bPlyPQj+obds+zcxMP6ht2z5cj0I/LEkSP83MTD8sSRI/PQpXP6ht2z7NzEw/" +
	"qG3bPs3MTD8sSRI/PQpXP6ht2z7NzEw/LEkSPz0KVz8sSRI/PQpXPyxJEj+uR2E/qG3bPj0KVz+obds+rkdhP6ht2z49Clc/LEkSP65HYT8sSRI/rkdhPyxJ" +
	"Ej8fhWs/qG3bPq5HYT+obds+H4VrP6ht2z6uR2E/LEkSPx+Faz8sSRI/H4VrPyxJEj+PwnU/qG3bPh+Faz+obds+j8J1P6ht2z4fhWs/LEkSP4/CdT8sSRI/" +
	"j8J1PyxJEj8AAIA/qG3bPo/CdT+obds+AACAP6ht2z6PwnU/LEkSPwAAgD8sSRI/AAAAACxJEj8K1yM9cts2PwrXIz0sSRI/CtcjPXLbNj8AAAAALEkSPwAA" +
	"AABy2zY/rkfhPnLbNj/NzMw+LEkSP83MzD5y2zY/zczMPixJEj+uR+E+cts2P65H4T4sSRI/j8L1PnLbNj+uR+E+LEkSP65H4T5y2zY/rkfhPixJEj+PwvU+" +
	"cts2P4/C9T4sSRI/uB4FP3LbNj+PwvU+LEkSP4/C9T5y2zY/j8L1PixJEj+4HgU/cts2P7geBT8sSRI/uB4FP3LbNj8pXA8/cts2PylcDz8sSRI/uB4FP3Lb" +
	"Nj8pXA8/LEkSP7geBT8sSRI/mpkZPyxJEj8pXA8/cts2P5qZGT9y2zY/KVwPP3LbNj+amRk/LEkSPylcDz8sSRI/CtcjPyxJEj+amRk/cts2PwrXIz9y2zY/" +
	"mpkZP3LbNj8K1yM/LEkSP5qZGT8sSRI/CtcjP3LbNj97FC4/LEkSPwrXIz8sSRI/exQuPyxJEj8K1yM/cts2P3sULj9y2zY/exQuP3LbNj/sUTg/LEkSP3sU" +
	"Lj8sSRI/7FE4PyxJEj97FC4/cts2P+xROD9y2zY/XI9CP3LbNj/sUTg/LEkSP+xROD9y2zY/7FE4PyxJEj9cj0I/cts2P1yPQj8sSRI/zcxMP3LbNj9cj0I/" +
	"LEkSP1yPQj9y2zY/XI9CPyxJEj/NzEw/cts2P83MTD8sSRI/zcxMP3LbNj89Clc/cts2Pz0KVz8sSRI/PQpXPyxJEj/NzEw/LEkSP83MTD9y2zY/PQpXP3Lb" +
	"Nj+uR2E/cts2P65HYT8sSRI/rkdhPyxJEj89Clc/LEkSPz0KVz9y2zY/H4VrPyxJEj+uR2E/cts2Px+Faz9y2zY/rkdhP3LbNj8fhWs/LEkSP65HYT8sSRI/" +
	"j8J1P3LbNj8fhWs/LEkSPx+Faz9y2zY/H4VrPyxJEj+PwnU/cts2P4/CdT8sSRI/j8J1PyxJEj8AAIA/cts2PwAAgD8sSRI/AACAP3LbNj+PwnU/LEkSP4/C" +
	"dT9y2zY/j8L1PrltWz+uR+E+cts2P65H4T65bVs/rkfhPnLbNj+PwvU+uW1bP4/C9T5y2zY/uB4FP7ltWz8pXA8/uW1bPylcDz9y2zY/uB4FP7ltWz8pXA8/" +
	"cts2P7geBT9y2zY/mpkZP7ltWz8pXA8/cts2PylcDz+5bVs/KVwPP3LbNj+amRk/uW1bP5qZGT9y2zY/CtcjP7ltWz+amRk/cts2P5qZGT+5bVs/mpkZP3Lb" +
	"Nj8K1yM/uW1bPwrXIz9y2zY/CtcjP3LbNj97FC4/uW1bP3sULj9y2zY/exQuP7ltWz8K1yM/cts2PwrXIz+5bVs/exQuP3LbNj/sUTg/uW1bP+xROD9y2zY/" +
	"7FE4P7ltWz97FC4/cts2P3sULj+5bVs/7FE4P7ltWz9cj0I/uW1bP1yPQj9y2zY/XI9CP3LbNj/sUTg/cts2P+xROD+5bVs/XI9CP7ltWz/NzEw/uW1bP83M" +
	"TD9y2zY/zcxMP3LbNj9cj0I/cts2P1yPQj+5bVs/PQpXP7ltWz/NzEw/cts2P83MTD+5bVs/zcxMP3LbNj89Clc/uW1bPz0KVz9y2zY/rkdhP7ltWz89Clc/" +
	"cts2Pz0KVz+5bVs/PQpXP3LbNj+uR2E/uW1bP65HYT9y2zY/H4VrP7ltWz+uR2E/cts2P65HYT+5bVs/rkdhP3LbNj8fhWs/uW1bPx+Faz9y2zY/"
)
const RIM_INDICES_B64 := (
	"AAACAAEAAwAFAAQABgAIAAcACQALAAoADAAOAA0ADwARABAAEgAUABMAFQAXABYAGAAaABkAGwAdABwAHgAgAB8AIQAjACIAJAAmACUAJwApACgAKgAsACsA" +
	"LQAvAC4AMAAyADEAMwA1ADQANgA4ADcAOQA7ADoAPAA+AD0APwBBAEAAQgBEAEMARQBHAEYASABKAEkASwBNAEwATgBQAE8AUQBTAFIAVABWAFUAVwBZAFgA" +
	"WgBcAFsAXQBfAF4AYABiAGEAYwBlAGQAZgBoAGcAaQBrAGoAbABuAG0AbwBxAHAAcgB0AHMAdQB3AHYAeAB6AHkAewB9AHwAfgCAAH8AgQCDAIIAhACGAIUA" +
	"hwCJAIgAigCMAIsAjQCPAI4AkACSAJEAkwCVAJQAlgCYAJcAmQCbAJoAnACeAJ0AnwChAKAAogCkAKMApQCnAKYAqACqAKkAqwCtAKwArgCwAK8AsQCzALIA" +
	"tAC2ALUAtwC5ALgAugC8ALsAvQC/AL4AwADCAMEAwwDFAMQAxgDIAMcAyQDLAMoAzADOAM0AzwDRANAA0gDUANMA1QDXANYA2ADaANkA2wDdANwA3gDgAN8A" +
	"4QDjAOIA5ADmAOUA5wDpAOgA6gDsAOsA7QDvAO4A8ADyAPEA8wD1APQA9gD4APcA+QD7APoA/AD+AP0A/wABAQABAgEEAQMBBQEHAQYBCAEKAQkBCwENAQwB" +
	"DgEQAQ8BEQETARIBFAEWARUBFwEZARgBGgEcARsBHQEfAR4BIAEiASEBIwElASQBJgEoAScBKQErASoBLAEuAS0BLwExATABMgE0ATMBNQE3ATYBOAE6ATkB" +
	"OwE9ATwBPgFAAT8BQQFDAUIBRAFGAUUBRwFJAUgBSgFMAUsBTQFPAU4BUAFSAVEBUwFVAVQBVgFYAVcBWQFbAVoBXAFeAV0BXwFhAWABYgFkAWMBZQFnAWYB" +
	"aAFqAWkBawFtAWwBbgFwAW8BcQFzAXIBdAF2AXUBdwF5AXgBegF8AXsBfQF/AX4BgAGCAYEBgwGFAYQBhgGIAYcBiQGLAYoBjAGOAY0BjwGRAZABkgGUAZMB" +
	"lQGXAZYBmAGaAZkBmwGdAZwBngGgAZ8BoQGjAaIBpAGmAaUBpwGpAagBqgGsAasBrQGvAa4BsAGyAbEBswG1AbQBtgG4AbcBuQG7AboBvAG+Ab0BvwHBAcAB" +
	"wgHEAcMBxQHHAcYByAHKAckBywHNAcwBzgHQAc8B0QHTAdIB1AHWAdUB1wHZAdgB2gHcAdsB3QHfAd4B4AHiAeEB4wHlAeQB5gHoAecB6QHrAeoB7AHuAe0B" +
	"7wHxAfAB8gH0AfMB9QH3AfYB+AH6AfkB+wH9AfwB/gEAAv8BAQIDAgICBAIGAgUCBwIJAggCCgIMAgsCDQIPAg4CEAISAhECEwIVAhQCFgIYAhcCGQIbAhoC" +
	"HAIeAh0CHwIhAiACIgIkAiMCJQInAiYCKAIqAikCKwItAiwCLgIwAi8CMQIzAjICNAI2AjUCNwI5AjgCOgI8AjsCPQI/Aj4CQAJCAkECQwJFAkQCRgJIAkcC" +
	"SQJLAkoCTAJOAk0CTwJRAlACUgJUAlMCVQJXAlYCWAJaAlkCWwJdAlwCXgJgAl8CYQJjAmICZAJmAmUCZwJpAmgCagJsAmsCbQJvAm4CcAJyAnECcwJ1AnQC" +
	"dgJ4AncCeQJ7AnoCfAJ+An0CfwKBAoACggKEAoMChQKHAoYCiAKKAokCiwKNAowCjgKQAo8CkQKTApIClAKWApUClwKZApgCmgKcApsCnQKfAp4CoAKiAqEC" +
	"owKlAqQCpgKoAqcCqQKrAqoCrAKuAq0CrwKxArACsgK0ArMCtQK3ArYCuAK6ArkCuwK9ArwCvgLAAr8CwQLDAsIC"
)
const RIM_VERTEX_COUNT: int = 708
const RIM_INDEX_COUNT: int = 708


const OUTER_SHADER_CODE := """
shader_type spatial;
render_mode cull_disabled, depth_draw_opaque, diffuse_lambert, specular_disabled;

uniform sampler2D cup_texture : source_color, filter_linear, repeat_enable;
uniform vec4 cup_tint : source_color = vec4(1.0);

void fragment() {
	// SceneKit contentsTransform:
	// U = U - 0.25
	// V = V * 4.0
	vec2 sample_uv = fract(vec2(UV.x - 0.25, UV.y * 4.0));
	vec4 texel = texture(cup_texture, sample_uv);
	ALBEDO = texel.rgb * cup_tint.rgb;
	ROUGHNESS = 1.0;
}
"""

const INNER_SHADER_CODE := """
shader_type spatial;
render_mode cull_disabled, depth_draw_opaque, diffuse_lambert, specular_disabled;

uniform sampler2D cup_texture : source_color, filter_linear, repeat_enable;

float mirrored_repeat(float value) {
	float wrapped = mod(value, 2.0);
	return 1.0 - abs(wrapped - 1.0);
}

void fragment() {
	// SceneKit contentsTransform:
	// U = U + 0.25, with mirrored-repeat wrapping
	// V = V, with repeat wrapping
	vec2 sample_uv = vec2(
		mirrored_repeat(UV.x + 0.25),
		fract(UV.y)
	);
	vec4 texel = texture(cup_texture, sample_uv);
	ALBEDO = texel.rgb;
	ROUGHNESS = 1.0;
}
"""

const RIM_SHADER_CODE := """
shader_type spatial;
render_mode cull_back, depth_draw_opaque, diffuse_lambert, specular_disabled;

void fragment() {
	ALBEDO = vec3(1.0);
	ROUGHNESS = 1.0;
}
"""

const CUP_TEXTURE_DIR := "res://pong/cups"
const DEFAULT_CUP_STYLE: int = 1
const DEFAULT_CUP_INNER_ID: int = 1
const DEFAULT_CUP_TINT := Color.WHITE
const EXPECTED_TEXTURE_SIZE := Vector2i(600, 300)
const CUP_OUTER_TEXTURE_MAP := {
	1: "res://pong/cups/cup1.png",
}

const CUP_INNER_TEXTURE_MAP := {
	1: "res://pong/cups/cup1_inner.png",
}

const CUP_STYLE_INNER_MAP := {
	1: 1,
}

@export_range(1, 999, 1) var cup_style: int = DEFAULT_CUP_STYLE
@export var cup_tint: Color = DEFAULT_CUP_TINT

var outer_texture: Texture2D
var inner_texture: Texture2D

var prev_cups: Array
var cups_in_play: Array = [0,1,2,3,4,5,6,7,8,9]
var random_positions: Dictionary = {}
var mirror_x: bool = false

var _outer_material: ShaderMaterial
var _inner_material: ShaderMaterial
var _rim_material: ShaderMaterial

var _resolved_outer_path: String = ""
var _resolved_inner_path: String = ""
var _resolved_inner_id: int = DEFAULT_CUP_INNER_ID
var _last_material_log_signature: String = ""
var _collision_layout_logged: bool = false

static var _cup_mesh: ArrayMesh
static var _white_texture: Texture2D
static var _instances: Array[WeakRef] = []
static var _default_outer_texture: Texture2D
static var _default_inner_texture: Texture2D
static var _style_texture_cache: Dictionary = {}


func dbg(parts: Variant) -> void:
	if DEBUG_CUPS:
		OpLog.d(LOG_TAG, parts)


func _ready() -> void:
	_register_instance()
	_materialize_cup_bodies()

	if outer_texture == null and _default_outer_texture != null:
		outer_texture = _default_outer_texture
	if inner_texture == null and _default_inner_texture != null:
		inner_texture = _default_inner_texture

	if outer_texture == null or inner_texture == null:
		var style_textures := _get_style_textures(cup_style)
		_resolved_outer_path = String(style_textures.outer_path)
		_resolved_inner_path = String(style_textures.inner_path)
		_resolved_inner_id = int(style_textures.inner_id)

		if outer_texture == null:
			outer_texture = style_textures.outer
		if inner_texture == null:
			inner_texture = style_textures.inner

	_build_materials()

	for cup: StaticBody3D in _cup_bodies():
		_build_cup_visual(cup)
		_build_cup_colliders(cup)
		_ensure_cup_markers(cup)


func _materialize_cup_bodies() -> void:
	var placeholders: Array[Node3D] = []

	for child: Node in get_children():
		if child is StaticBody3D:
			var existing_body := child as StaticBody3D
			existing_body.collision_layer = CUP_COLLISION_LAYER
			existing_body.collision_mask = CUP_COLLISION_MASK
			existing_body.input_ray_pickable = false
			continue

		var placeholder := child as Node3D
		if placeholder != null and _is_cup_node_name(String(placeholder.name)):
			placeholders.append(placeholder)

	for placeholder: Node3D in placeholders:
		var child_index := placeholder.get_index()
		var cup_name := placeholder.name
		var cup_transform := placeholder.transform
		var cup_visible := placeholder.visible
		var cup_process_mode := placeholder.process_mode

		remove_child(placeholder)
		placeholder.queue_free()

		var body := StaticBody3D.new()
		body.name = cup_name
		body.transform = cup_transform
		body.visible = cup_visible
		body.process_mode = cup_process_mode
		body.collision_layer = CUP_COLLISION_LAYER
		body.collision_mask = CUP_COLLISION_MASK
		body.input_ray_pickable = false

		add_child(body)
		move_child(body, child_index)


func _is_cup_node_name(node_name: String) -> bool:
	if not node_name.begins_with("cup"):
		return false

	var suffix := node_name.trim_prefix("cup")
	return not suffix.is_empty() and suffix.is_valid_int()


func _exit_tree() -> void:
	_prune_instances(self)


static func set_cup_texture(tex: Texture2D) -> void:
	_default_outer_texture = tex
	_prune_instances()

	for weak: WeakRef in _instances:
		var rack := weak.get_ref() as Cups
		if is_instance_valid(rack):
			rack.set_cup_textures(tex, rack.inner_texture)


static func set_default_cup_textures(outer: Texture2D, inner: Texture2D) -> void:
	_default_outer_texture = outer
	_default_inner_texture = inner
	_prune_instances()

	for weak: WeakRef in _instances:
		var rack := weak.get_ref() as Cups
		if is_instance_valid(rack):
			rack.set_cup_textures(outer, inner)


static func outer_material() -> Material:
	_prune_instances()

	for weak: WeakRef in _instances:
		var rack := weak.get_ref() as Cups
		if is_instance_valid(rack):
			return rack._outer_material

	return null


static func inner_material() -> Material:
	_prune_instances()

	for weak: WeakRef in _instances:
		var rack := weak.get_ref() as Cups
		if is_instance_valid(rack):
			return rack._inner_material

	return null


static func _prune_instances(remove_instance: Cups = null) -> void:
	var keep: Array[WeakRef] = []

	for weak: WeakRef in _instances:
		var rack := weak.get_ref() as Cups
		if not is_instance_valid(rack):
			continue
		if rack == remove_instance:
			continue
		keep.append(weak)

	_instances = keep


func _register_instance() -> void:
	_prune_instances()

	for weak: WeakRef in _instances:
		if weak.get_ref() == self:
			return

	_instances.append(weakref(self))


func set_cup_style(style: int, tint: Color = Color.WHITE) -> void:
	var resolved_style := _resolve_cup_style(style)
	cup_style = resolved_style
	cup_tint = tint

	var style_textures := _get_style_textures(resolved_style)
	outer_texture = style_textures.outer
	inner_texture = style_textures.inner
	_resolved_outer_path = String(style_textures.outer_path)
	_resolved_inner_path = String(style_textures.inner_path)
	_resolved_inner_id = int(style_textures.inner_id)
	_last_material_log_signature = ""

	if (
		_outer_material == null or
		_inner_material == null or
		_rim_material == null
	):
		_build_materials()
	else:
		_apply_material_textures()


func set_cup_tint(tint: Color) -> void:
	cup_tint = tint

	if _outer_material == null:
		_build_materials()
	else:
		_apply_material_textures()


func set_cup_textures(outer: Texture2D, inner: Texture2D) -> void:
	outer_texture = outer
	inner_texture = inner
	_resolved_outer_path = "<runtime>"
	_resolved_inner_path = "<runtime>"
	_resolved_inner_id = -1
	_last_material_log_signature = ""

	if (
		_outer_material == null or
		_inner_material == null or
		_rim_material == null
	):
		_build_materials()
	else:
		_apply_material_textures()


static func has_cup_style(style: int) -> bool:
	return CUP_OUTER_TEXTURE_MAP.has(style)


static func available_cup_styles(max_style: int = 999) -> Array[int]:
	var styles: Array[int] = []

	for key in CUP_OUTER_TEXTURE_MAP.keys():
		var style := int(key)
		if style <= max_style:
			styles.append(style)

	styles.sort()
	return styles


static func clear_style_texture_cache() -> void:
	_style_texture_cache.clear()


static func _resolve_cup_style(style: int) -> int:
	if has_cup_style(style):
		return style

	if style != DEFAULT_CUP_STYLE:
		OpLog.w(LOG_TAG, [
			"Unknown cup style=", style,
			" fallback=", DEFAULT_CUP_STYLE
		])

	return DEFAULT_CUP_STYLE


static func _cup_outer_path(style: int) -> String:
	return String(CUP_OUTER_TEXTURE_MAP.get(style, ""))


static func _inner_id_for_style(style: int) -> int:
	return int(CUP_STYLE_INNER_MAP.get(style, DEFAULT_CUP_INNER_ID))


static func _cup_inner_path_from_id(inner_id: int) -> String:
	return String(CUP_INNER_TEXTURE_MAP.get(inner_id, ""))


static func _cup_inner_path(style: int) -> String:
	return _cup_inner_path_from_id(_inner_id_for_style(style))


static func _get_style_textures(style: int) -> Dictionary:
	var resolved_style := _resolve_cup_style(style)

	if _style_texture_cache.has(resolved_style):
		return _style_texture_cache[resolved_style]

	var requested_outer_path := _cup_outer_path(resolved_style)
	var default_outer_path := _cup_outer_path(DEFAULT_CUP_STYLE)
	var requested_inner_id := _inner_id_for_style(resolved_style)
	var requested_inner_path := _cup_inner_path_from_id(requested_inner_id)
	var default_inner_path := _cup_inner_path_from_id(DEFAULT_CUP_INNER_ID)

	var outer := _load_cup_texture(requested_outer_path)
	if outer == null and requested_outer_path != default_outer_path:
		OpLog.w(LOG_TAG, [
			"Missing cup outer texture style=", resolved_style,
			" path=", requested_outer_path,
			" fallback=", default_outer_path
		])
		outer = _load_cup_texture(default_outer_path)

	var inner := _load_cup_texture(requested_inner_path)
	if inner == null and requested_inner_path != default_inner_path:
		OpLog.i(LOG_TAG, [
			"Missing cup inner texture style=", resolved_style,
			" inner_id=", requested_inner_id,
			" path=", requested_inner_path,
			" fallback=", default_inner_path
		])
		inner = _load_cup_texture(default_inner_path)

	if outer == null:
		outer = _get_white_texture()
	if inner == null:
		inner = _get_white_texture()

	var textures := {
		"outer": outer,
		"inner": inner,
		"style": resolved_style,
		"inner_id": requested_inner_id,
		"outer_path": requested_outer_path,
		"inner_path": requested_inner_path,
	}

	_style_texture_cache[resolved_style] = textures
	return textures


static func _load_cup_texture(path: String) -> Texture2D:
	if not ResourceLoader.exists(path):
		return null

	var texture := ResourceLoader.load(path) as Texture2D
	if texture == null:
		OpLog.w(LOG_TAG, ["Failed to load cup texture path=", path])
		return null

	var actual_size := Vector2i(texture.get_width(), texture.get_height())
	if actual_size != EXPECTED_TEXTURE_SIZE:
		OpLog.w(LOG_TAG, [
			"Unexpected cup texture size path=", path,
			" expected=", EXPECTED_TEXTURE_SIZE,
			" actual=", actual_size
		])

	return texture


func _build_materials() -> void:
	if _outer_material == null:
		var outer_shader := Shader.new()
		outer_shader.code = OUTER_SHADER_CODE

		_outer_material = ShaderMaterial.new()
		_outer_material.shader = outer_shader

	if _inner_material == null:
		var inner_shader := Shader.new()
		inner_shader.code = INNER_SHADER_CODE

		_inner_material = ShaderMaterial.new()
		_inner_material.shader = inner_shader

	if _rim_material == null:
		var rim_shader := Shader.new()
		rim_shader.code = RIM_SHADER_CODE

		_rim_material = ShaderMaterial.new()
		_rim_material.shader = rim_shader

	_apply_material_textures()


func _apply_material_textures() -> void:
	var applied_outer := outer_texture if outer_texture != null else _get_white_texture()
	var applied_inner := inner_texture if inner_texture != null else _get_white_texture()

	if _outer_material != null:
		_outer_material.set_shader_parameter("cup_texture", applied_outer)
		_outer_material.set_shader_parameter("cup_tint", cup_tint)

	if _inner_material != null:
		_inner_material.set_shader_parameter("cup_texture", applied_inner)

	_log_material_state(applied_outer, applied_inner)


func _log_material_state(applied_outer: Texture2D, applied_inner: Texture2D) -> void:
	var outer_size := Vector2i(
		applied_outer.get_width(),
		applied_outer.get_height()
	)
	var inner_size := Vector2i(
		applied_inner.get_width(),
		applied_inner.get_height()
	)
	var signature := "%s|%d|%s|%s|%s|%s" % [
		name,
		cup_style,
		str(cup_tint),
		_resolved_outer_path,
		_resolved_inner_path,
		str(outer_size) + "/" + str(inner_size)
	]

	if signature == _last_material_log_signature:
		return

	_last_material_log_signature = signature
	OpLog.i(LOG_TAG, [
		"cup_material rack=", name,
		" style=", cup_style,
		" tint=", cup_tint,
		" outer=", _resolved_outer_path,
		" outerSize=", outer_size,
		" innerId=", _resolved_inner_id,
		" inner=", _resolved_inner_path,
		" innerSize=", inner_size,
		" outerMat=", _outer_material.get_instance_id() if _outer_material != null else -1,
		" innerMat=", _inner_material.get_instance_id() if _inner_material != null else -1
	])


static func _get_white_texture() -> Texture2D:
	if _white_texture != null:
		return _white_texture

	var image := Image.create(1, 1, false, Image.FORMAT_RGBA8)
	image.fill(Color.WHITE)
	_white_texture = ImageTexture.create_from_image(image)
	return _white_texture


static func _decode_vec3_array(encoded: String, count: int) -> PackedVector3Array:
	var bytes: PackedByteArray = Marshalls.base64_to_raw(encoded)
	var output := PackedVector3Array()
	output.resize(count)

	for i in count:
		var offset: int = i * 12
		output[i] = Vector3(
			bytes.decode_float(offset),
			bytes.decode_float(offset + 4),
			bytes.decode_float(offset + 8)
		)

	return output


static func _decode_vec2_array(encoded: String, count: int) -> PackedVector2Array:
	var bytes: PackedByteArray = Marshalls.base64_to_raw(encoded)
	var output := PackedVector2Array()
	output.resize(count)

	for i in count:
		var offset: int = i * 8
		output[i] = Vector2(
			bytes.decode_float(offset),
			bytes.decode_float(offset + 4)
		)

	return output


static func _decode_index_array(encoded: String, count: int) -> PackedInt32Array:
	var bytes: PackedByteArray = Marshalls.base64_to_raw(encoded)
	var output := PackedInt32Array()
	output.resize(count)

	for i in count:
		output[i] = int(bytes.decode_u16(i * 2))

	return output


static func _transform_vertices(
	source: PackedVector3Array,
	scale_value: float,
	offset: Vector3
) -> PackedVector3Array:
	var output := PackedVector3Array()
	output.resize(source.size())

	for i in source.size():
		output[i] = source[i] * scale_value + offset

	return output


static func _add_exact_surface(
	mesh: ArrayMesh,
	vertices_b64: String,
	normals_b64: String,
	uvs_b64: String,
	indices_b64: String,
	vertex_count: int,
	index_count: int,
	vertex_offset: Vector3,
	surface_name: String
) -> void:
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)

	arrays[Mesh.ARRAY_VERTEX] = _transform_vertices(
		_decode_vec3_array(vertices_b64, vertex_count),
		VISUAL_SCALE,
		vertex_offset
	)
	arrays[Mesh.ARRAY_NORMAL] = _decode_vec3_array(normals_b64, vertex_count)
	arrays[Mesh.ARRAY_TEX_UV] = _decode_vec2_array(uvs_b64, vertex_count)
	arrays[Mesh.ARRAY_INDEX] = _decode_index_array(indices_b64, index_count)

	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	mesh.surface_set_name(mesh.get_surface_count() - 1, surface_name)


static func _build_cup_mesh() -> ArrayMesh:
	if _cup_mesh != null:
		return _cup_mesh

	var mesh := ArrayMesh.new()

	_add_exact_surface(
		mesh,
		FRONT_VERTICES_B64,
		FRONT_NORMALS_B64,
		FRONT_UVS_B64,
		FRONT_INDICES_B64,
		FRONT_VERTEX_COUNT,
		FRONT_INDEX_COUNT,
		BODY_VERTEX_OFFSET,
		"front"
	)

	_add_exact_surface(
		mesh,
		BACK_VERTICES_B64,
		BACK_NORMALS_B64,
		BACK_UVS_B64,
		BACK_INDICES_B64,
		BACK_VERTEX_COUNT,
		BACK_INDEX_COUNT,
		BODY_VERTEX_OFFSET,
		"back"
	)

	_add_exact_surface(
		mesh,
		RIM_VERTICES_B64,
		RIM_NORMALS_B64,
		RIM_UVS_B64,
		RIM_INDICES_B64,
		RIM_VERTEX_COUNT,
		RIM_INDEX_COUNT,
		RIM_VERTEX_OFFSET,
		"rim"
	)

	_cup_mesh = mesh
	return _cup_mesh

func _build_cup_visual(cup: StaticBody3D) -> void:
	var existing := (
		cup.get_node_or_null("CupMesh")
		as MeshInstance3D
	)

	if existing == null:
		for child: Node in cup.get_children():
			if (
				child is CSGMesh3D or
				child is MeshInstance3D
			):
				cup.remove_child(child)
				child.queue_free()

		existing = MeshInstance3D.new()
		existing.name = "CupMesh"
		existing.mesh = _build_cup_mesh()

		cup.add_child(existing)
		cup.move_child(existing, 0)
	else:
		existing.mesh = _build_cup_mesh()

	existing.position = Vector3.ZERO
	existing.scale = Vector3.ONE

	if name == &"cups1":
		existing.rotation = Vector3(
			0.0,
			PI,
			0.0
		)
	else:
		existing.rotation = Vector3.ZERO

	existing.set_surface_override_material(
		0,
		_outer_material
	)

	existing.set_surface_override_material(
		1,
		_inner_material
	)

	existing.set_surface_override_material(
		2,
		_rim_material
	)

func _build_cup_colliders(cup: StaticBody3D) -> void:
	cup.collision_layer = CUP_COLLISION_LAYER
	cup.collision_mask = CUP_COLLISION_MASK
	cup.input_ray_pickable = false

	for child: Node in cup.get_children():
		if child is CollisionShape3D:
			cup.remove_child(child)
			child.queue_free()

	for i in WALL_POSITIONS.size():
		var collision := CollisionShape3D.new()
		collision.name = "CupWall%d" % i

		var box := BoxShape3D.new()
		box.size = WALL_SIZE

		collision.shape = box
		collision.position = WALL_POSITIONS[i]
		collision.basis = _wall_basis_from_position(WALL_POSITIONS[i])
		cup.add_child(collision)

	var base := CollisionShape3D.new()
	base.name = "CupBase"

	var base_box := BoxShape3D.new()
	base_box.size = BASE_SIZE

	base.shape = base_box
	base.position = Vector3.ZERO
	cup.add_child(base)

	if not _collision_layout_logged:
		_collision_layout_logged = true
		_log_collision_layout()


func _wall_basis_from_position(wall_position: Vector3) -> Basis:
	var radial := Vector3(wall_position.x, 0.0, wall_position.z).normalized()
	var flare_sin := sin(WALL_FLARE_RADIANS)
	var flare_cos := cos(WALL_FLARE_RADIANS)

	var local_y := Vector3(
		radial.x * flare_sin,
		flare_cos,
		radial.z * flare_sin
	).normalized()
	var local_z := Vector3(
		radial.x * flare_cos,
		-flare_sin,
		radial.z * flare_cos
	).normalized()
	var local_x := local_y.cross(local_z).normalized()

	return Basis(local_x, local_y, local_z).orthonormalized()


func _log_collision_layout() -> void:
	var min_opening := INF
	var max_opening := 0.0

	for i in WALL_POSITIONS.size():
		var basis := _wall_basis_from_position(WALL_POSITIONS[i])
		var top_center := WALL_POSITIONS[i] + basis.y * (WALL_SIZE.y * 0.5)
		var top_inner := top_center - basis.z * (WALL_SIZE.z * 0.5)
		var opening_radius := Vector2(top_inner.x, top_inner.z).length()
		min_opening = minf(min_opening, opening_radius)
		max_opening = maxf(max_opening, opening_radius)

	OpLog.i(LOG_TAG, [
		"collision_layout rack=", name,
		" wallCount=", WALL_POSITIONS.size(),
		" wallSize=", WALL_SIZE,
		" baseSize=", BASE_SIZE,
		" topInnerRadius=", Vector2(min_opening, max_opening),
		" markerY=", Vector2(BALL_REST_MARKER_Y, BALL_DAMP_MARKER_Y)
	])


func _ensure_cup_markers(cup: StaticBody3D) -> void:
	_ensure_marker(cup, "ball", Vector3(0.0, BALL_DAMP_MARKER_Y, 0.0))
	_ensure_marker(cup, "ball2", Vector3(0.0, BALL_REST_MARKER_Y, 0.0))


func _ensure_marker(cup: StaticBody3D, marker_name: String, marker_position: Vector3) -> void:
	var marker := cup.get_node_or_null(marker_name) as Marker3D

	if marker == null:
		marker = Marker3D.new()
		marker.name = marker_name
		cup.add_child(marker)

	marker.position = marker_position


func _cup_bodies() -> Array[StaticBody3D]:
	var result: Array[StaticBody3D] = []

	for child: Node in get_children():
		var cup := child as StaticBody3D
		if cup != null:
			result.append(cup)

	return result


func _cup_at(index: int) -> StaticBody3D:
	var bodies := _cup_bodies()

	if index < 0 or index >= bodies.size():
		return null

	return bodies[index]


func reset_cups(cups: Array) -> void:
	dbg(["reset_cups name=", name, " cups=", cups])

	var all_cups := _cup_bodies()

	for cup: StaticBody3D in all_cups:
		cup.name = "cupremoved"

	for cup_idx in all_cups.size():
		var cup: StaticBody3D = all_cups[cup_idx]
		cup.name = "cup" + str(cup_idx + 1)
		cup.visible = true
		cup.collision_layer = 1

	cups_in_play = [0,1,2,3,4,5,6,7,8,9]
	set_cups_in_play(cups)


func apply_random_positions(positions: Array) -> void:
	random_positions.clear()

	for i in range(min(positions.size(), 10)):
		random_positions[i] = positions[i]

	dbg([
		"apply_random_positions name=", name,
		" count=", random_positions.size(),
		" mirrorX=", mirror_x
	])


func set_cups_in_play(cups: Array) -> void:
	dbg(["set_cups_in_play name=", name, " from=", cups_in_play, " to=", cups])

	for cup_idx in cups_in_play:
		if cup_idx not in cups:
			var cup := _cup_at(cup_idx)
			if cup == null:
				continue

			cup.visible = false
			cup.name = "cupremoved"
			cup.collision_layer = 0

	cups_in_play = cups.duplicate()

	if random_positions.size() > 0:
		_arrange_random()
	else:
		arrangeCups()


func remove_cup(cup_num: int) -> void:
	var cup_index: int = cup_num - 1
	var cup := _cup_at(cup_index)

	if cup == null:
		OpLog.w(LOG_TAG, [
			"remove_cup invalid cup=", cup_num,
			" childCount=", _cup_bodies().size()
		])
		return

	if cup_index not in cups_in_play:
		OpLog.w(LOG_TAG, [
			"remove_cup already_removed cup=", cup_num,
			" remaining=", cups_in_play
		])
		return

	cup.name = "cupremoved"
	cup.collision_layer = 0

	var start_pos: Vector3 = cup.position
	var exit_x_sign: float = 1.0 if start_pos.x >= 0.0 else -1.0
	var lifted_pos: Vector3 = start_pos + Vector3(0.0, CUP_REMOVE_LIFT_HEIGHT, 0.0)
	var exit_pos: Vector3 = Vector3(
		exit_x_sign * CUP_REMOVE_EXIT_X,
		lifted_pos.y,
		lifted_pos.z
	)

	var anim := get_tree().create_tween()
	anim.tween_property(cup, "position", lifted_pos, CUP_REMOVE_LIFT_DURATION) \
		.set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)
	anim.tween_property(cup, "position", exit_pos, CUP_REMOVE_SLIDE_DURATION) \
		.set_trans(Tween.TRANS_QUAD).set_ease(Tween.EASE_IN)
	anim.tween_callback(func() -> void:
		if is_instance_valid(cup):
			cup.visible = false
	)
	anim.play()

	cups_in_play.erase(cup_index)

	OpLog.i(LOG_TAG, [
		"remove_cup name=", name,
		" cup=", cup_num,
		" remaining=", cups_in_play
	])

	if random_positions.size() == 0:
		arrangeCups()


func _arrange_random() -> void:
	dbg([
		"arrange_random name=", name,
		" inPlay=", cups_in_play,
		" positions=", random_positions.size()
	])

	for cup_idx in cups_in_play:
		if not random_positions.has(cup_idx):
			continue

		var cup := _cup_at(cup_idx)
		if cup == null:
			continue

		cup.position = random_positions[cup_idx]


func arrangeCups() -> void:
	var num_cups: int = cups_in_play.size()

	dbg([
		"arrange_cups name=", name,
		" count=", num_cups,
		" inPlay=", cups_in_play
	])

	if num_cups != 6 and num_cups != 3:
		return

	var target_positions: Array[Vector3] = []

	if num_cups == 6:
		target_positions = [
			Vector3(0.0, -0.597, -1.967),
			Vector3(-0.071, -0.597, -2.087),
			Vector3(0.071, -0.597, -2.087),
			Vector3(-0.142, -0.597, -2.207),
			Vector3(0.0, -0.597, -2.207),
			Vector3(0.142, -0.597, -2.207),
		]
	else:
		target_positions = [
			Vector3(0.0, -0.597, -2.027),
			Vector3(-0.071, -0.597, -2.147),
			Vector3(0.071, -0.597, -2.147),
		]

	var tween := get_tree().create_tween()
	tween.set_loops(1)

	for cup_idx in cups_in_play.size():
		var original_index: int = cups_in_play[cup_idx]
		var cup := _cup_at(original_index)

		if cup == null:
			continue

		cup.name = "cup" + str(cup_idx + 1)
		tween.tween_property(
			cup,
			"position",
			target_positions[cup_idx],
			0.1 if cup_idx < 2 else 0.05
		)

	tween.play()

	if num_cups == 6:
		cups_in_play = [0,1,2,3,4,5]
	else:
		cups_in_play = [0,1,2]
